### ISSUE TITLE
Support Multiple providers of the same kind

### ISSUE THREAD

**Issue by yarbelk** [pennersr/django-allauth#1002]
A very large feature request - Support multiple SocialApps of the same provider.
- in some places this will help clean up some of the code conceptually - using standard ORM FK instead of lots of helper methods and callbacks.
- Useful for those people who are running sites with a Facebook Business account and lots of apps (additional strangeness here b/c of unique UIDs).  Or are building api services that make use of the same.

If there is interest in this, I'd love to contribute.

**Comment by ivanvenosdel** [comment]
I would like this feature as my site would like to offer two companion applications on the same social provider. So if a user signs in or connects to a provider using an app and then signs-in/connects a second app with the same provider it should re-use the same social account (which should be fine because social account has an FK to provider, not app). 

To me this all seems possible to implement without the need for model changes or making them swap-able. If I am right the feature would be far smaller in scope but am I missing something?

**Comment by esabunor** [comment]
@ivanvenosdel Did you "put in the time" for this feature maybe i could use your fork or something. :)
@pennersr I would like this feature as well because as @yarbelk  said:

- Useful for those people who are running sites with a Facebook Business account and lots of apps (additional strangeness here b/c of unique UIDs). Or are building api services that make use of the same.

I willing to contribute a PR as well.

**Comment by hishamkaram** [comment]
@pennersr  any progress on this issue?

**Comment by skumarcm** [comment]
This feature may be an important one as more mobile applications are being developed based on the same webserver.
Hence there could be multiple mobile apps that allow users to login through the same provider (eg. facebook) but still want to deliver the service through the same webserver powered by allauth.

Is there a solution available for this already? Or any plans to integrate this feature with django allauth?

**Comment by delton-ecometrica** [comment]
Has there been any update on this feature, to havet multiple social apps for the same provider

**Comment by yarbelk** [comment]
I'm not involved in the project that gave rise to this.  I think its a great feature that someone should do, but I won't be the one to do it.  Feel free to have someone take over.

**Comment by gboor** [comment]
Multiple apps for the same provider is one thing, but when talking about self-hosted providers - like Keycloak - having multiple providers isn't a bad idea either...

Or maybe just move the endpoint URL and realm for Keycloak into the config rather than setting it via env variables.

I might have a look at this in a few weeks, when I have some time.

**Comment by derek-adair** [comment]
Seems valid, @pennersr seems like there are people interested in contributing and need guidance on this one if it's desirable or not.

**Comment by Ramon-W** [comment]
@pennersr Is there any plans of this being completed? I am looking for this functionality in my application.

**Comment by pennersr** [comment]
This is already working for OIDC based providers. So, depending on the providers you need to support this might already just work.

**Comment by pennersr** [comment]
For OIDC and SAML, you can setup one provider with multiple apps, all of which can be used to sign in. For other providers, such as e.g. Apple, you can also configure multiple apps, though if you do so it may become ambiguous which one should be used when signing in. In this case, you can add `{"setting": {"hidden": True",...}}` to the app used for mobile authentication. All in all, I think this topic is sufficiently covered right now. Closing -- feel free to reopen with a clear use case scenario if you find there is still something missing.

**Comment by yarbelk** [comment]
Yay! It's finished

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1002
