### ISSUE TITLE
Emtpy fields when using facebook login

### ISSUE THREAD

**Issue by garcianavalon** [pennersr/django-allauth#1086]
Hi,
I'm using django and django-allauth. I can successfully authenticate a user using the facebook provider. The problem is that the created user object has all fields empty (first name, last name and email) and the username set to 'user' (which I asume is the default value for the generator). I also have a social account object associated with this user, which has the following data in the Extra data field:

    {"name": "my_first_name my_second_name", "id": "my_uuid"}

I've checked overriding the SocialAccountAdapter [populate_user function](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/adapter.py#L71) but the data parameter contains a dictionary where first name, last name and email are empty.

Searching up the code, in https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/base.py#L50 the response already comes with only 

    {"name": "my_first_name my_second_name", "id": "my_uuid"}

so I asume I have a configuration error of some sort with the Facebook provider. Any ideas?

Thanks for any help.

My facebook settings:
```
SOCIALACCOUNT_PROVIDERS = {  
    'facebook': {  
        'SCOPE': [  
            'email',  
            'public_profile',  
            'user_friends'  
        ],  
        'FIELDS': [  
            'id',  
            'email',  
            'name',  
            'first_name',  
            'last_name',  
            'verified',  
            'locale',  
            'timezone',  
            'link',  
            'gender',  
            'updated_time'  
        ],  
        'AUTH_PARAMS': {  
            #'auth_type': 'reauthenticate'  
        },  
        'METHOD': 'oauth2',  
        #'LOCALE_FUNC': 'path.to.callable',  
        'VERIFIED_EMAIL': True,  
        'VERSION': 'v2.4'  
    }
}  
```

**Comment by ncp1113** [comment]
I see that you have not filled in 'LOCALE_FUNC'.  If you are in the US, use 
'LOCALE_FUNC': lambda request: 'en_US'.  There is an xml file with Facebook locales at https://www.facebook.com/translations/FacebookLocales.xml which allauth uses.
However, I did test on my own project where I commented out 'LOCALE_FUNC' and it worked okay.  Looking at the code at django-allauth/allauth/socialaccount/providers/facebook/locale.py It looks like if you don't supply LOCALE_FUNC allauth will try to guess what is should be and default to en-US if it can't guess.  

So I doubt this is the problem, but it can't hurt to try putting something in there.

**Comment by dj4b1n** [comment]
Hey @garcianavalon, I'm having a similar problem and can't find much else online about it. Were you able to solve this?

**Comment by dj4b1n** [comment]
Okay @garcianavalon I just solved it (at least for myself anyway). I was running an older version of allauth (from late April), but I then realized that some of these changes were supported in later versions so I did a pip install django-allauth --upgrade to get the newest version. That led me to two other problems which I was able to solve using the changelog (http://django-allauth.readthedocs.org/en/latest/changelog.html).

- I got a merge conflict from an older migration I had and the migration 0002_email_max_length, but the contents of the migration I had were already in the 0002_email_max_length migration, so I deleted my older migration which fixed that.
- I then got a "No module named context_processors" error because I still had the allauth context processors in my settings file which are now no longer used (see "From 0.21.0" in the changelog). The fix for that was to just remove them ('allauth.account.context_processors.account', 'allauth.socialaccount.context_processors.socialaccount'). 

And now the extra_data field is populating as expected :) Hope that helps!

**Comment by garcianavalon** [comment]
Hey @dj4b1n thanks for your answer. I had to stop working on this project due to other work to do so I couldn't fix it properly. I will try updating and starting from scratch again and see if it works for me too :)

Could you paste here your settings? That way I could check that everything is correctly set up.
Thanks!

**Comment by dj4b1n** [comment]
SOCIALACCOUNT_PROVIDERS = {
    'facebook': {
        'SCOPE': ['email', 'public_profile', 'user_friends'],
        'METHOD': 'js_sdk',
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'friends'
            ]
        }
    }

**Comment by garcianavalon** [comment]
Thanks @dj4b1n !
After upgrading to v.023 I cant get the user data after authentication with facebook. :)

**Comment by dj4b1n** [comment]
Woohoo \o/ !

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1086
