### ISSUE TITLE
Is there a built-in way to limit users to a single email address?

### ISSUE THREAD

**Issue by hakanb** [pennersr/django-allauth#1109]
My project doesn't have much use for multiple emails per user, so in the interest of simplicity we'd like to limit users to a single email address.

I realize I can probably accomplish this in a naive way by overriding the email_confirmed signal and deleting all other EmailAddresses and EmailConfirmations associated with the user, but is there a built-in way to achieve this? 

Thanks for all the great work.

**Comment by aellerton** [comment]
Could you just remove the ui to add email addresses?

**Comment by manubellido** [comment]
The problem with this is that the endpoint /accounts/email is supported by the app which will give you 500 since the template was not found or something like that? I am not aware of a way to disable/override a specific url from an installed app.

**Comment by manubellido** [comment]
It seems that you can override urls if you listed before the default ones. I tried this and works so far.
```python
from django.views.defaults import page_not_found
...
url(r"^accounts/email/$", page_not_found, name="account_email"),
url(r"^accounts/', include('allauth.urls')),
...
```

**Comment by pennersr** [comment]
There is no built-in way, but it is easy to accomplish as described above.

**Comment by ekerstein** [comment]
This issue is 4 years old but I have the same question. Allauth newb here... I set it up on a test project and I want to only allow users to have one emails. Frankly, this is the only little thing that's preventing me from using the package.
Is the technique above (overriding the urls) still the best way to do it?

**Comment by pennersr** [comment]
Note that users should at all times be able to change their own email address without locking themselves out. So, users would need to be able to have at least two email addresses no matter what. The current one, and a new pending (unverified) one.

**Comment by ekerstein** [comment]
@pennersr Agree, but in my experience most sites have a simple form that lets you type in your new email address, and then a confirmation email is sent. If the confirmation is never clicked, the old email address remains. 

I'd say most sites do it that way, although I just checked GitHub and they appear to show multiple address. However, I would argue that's mainly because they allow you to receive notifications on a different email than your main login email.

If allauth is opinionated about allowing multiple email addresses to be added, that's fine. I'm still learning. Just trying to figure out my different options or whether I need to write my own.

**Comment by pennersr** [comment]
@ekerstein You do not need to expose the email management view, simply remove it from your urls.

**Comment by Abishek05** [comment]
> It seems that you can override urls if you listed before the default ones. I tried this and works so far.
> 
> ```python
> from django.views.defaults import page_not_found
> ...
> url(r"^accounts/email/$", page_not_found, name="account_email"),
> url(r"^accounts/', include('allauth.urls')),
> ...
> ```

page_not_found view now accepts a second parameter, the "exception" that triggered the error.
You may need to modify your code like this:-

```python
from django.views.defaults import page_not_found

urlpatterns = [
    path('accounts/email/', page_not_found, {'exception': Exception('Not Found')}, name="account_email"),
    path('accounts/', include('allauth.urls')),
]
```

**Comment by typonaut** [comment]
I am certain that I must have found this online somewhere, but I cannot now find a raference. Here is a solution for the user having a single email address (sorry it is uncredited):

```
models.py

from allauth.account.models import EmailAddress
from allauth.account.signals import email_confirmed

@receiver(email_confirmed)
def update_user_email(sender, request, email_address, **kwargs):
    # Once the email address is confirmed, make new email_address primary.
    # This also sets user.email to the new email address.
    # email_address is an instance of allauth.account.models.EmailAddress
    email_address.set_as_primary()
    # Get rid of old email addresses
    stale_addresses = EmailAddress.objects.filter(
        user=email_address.user).exclude(primary=True).delete()
```

**Comment by Sabrebar** [comment]
Thanks for your answers, Now If I want to create a form (with password, new_email) the user can use to change his email address, how can I do that? Maybe there is a way using built-in allauth forms?
I couldn't find the answer elsewhere

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1109
