### ISSUE TITLE
__iexact and .get() while fetching user

### ISSUE THREAD

**Issue by avneesh91** [pennersr/django-allauth#1122]
allauth/account/auth_backends.py 

query = {username_field+'__iexact': username}

user = User.objects.get(**query)

Why does django all auth do an __iexact while extracting users from the DB when the usernames in django are case senstive.

The above gives a multiple object  returned exception because it's doing a .get instead of a fiter.

Any help???

**Comment by pennersr** [comment]
Having case sensitive usernames results in a horrible user experience. Have a look here for more background information on the topic:

https://code.djangoproject.com/ticket/2273

The only reason usernames are case sensitive in Django is legacy, and the fact that the developers don't have the time to set things straight (quote: " We just don't have time.")

So `iexact` is by design ...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1122
