### ISSUE TITLE
Tutorial insufficient to obtain working setup

### ISSUE THREAD

**Issue by velis74** [pennersr/django-allauth#1129]
Python 3.4 Django 1.8 allauth 0.23

I just installed allauth expecting to get an easy way into social logins.

Did everything [this page](http://django-allauth.readthedocs.org/en/latest/installation.html) suggested. Used OAuth2 with Google as a first attempt. Please note that I have found nothing of help in any of the following pages of the documentation. They are all useful later on when one needs advanced stuff.

I'm getting mixed results with this:

* If I try to login via Google, google processes that OK, but the callback url ( localhost/accounts/google/login/callback/?state=(some session token) ) then says **Social network login failure**. Please note that example app in this repository has the same effect, only that it also says **Important: Authentication via OAuth based providers will not work until you setup proper applicaton credentials.** The link points to admin page where I can set up social apps (which I did).
* If I try to login via localhost/admin, only the default Django login dialog is shown. Same with django REST framework. Perhaps this is intended. Would be nice if tutorial explained how to replace these login prompts with allauth's one.
* If I go to localhost/accounts/login, I get a plain page, clearly without any formatting. Judging by templates content (and rendered output), this is intentional
* If I login with ordinary admin account that I created in Django before, it moves to localhost/accounts/profile/ , but that's a dud page and I get Django crash dump explaining that /profile does not exist. URL parsing list shows that this is actually the case. I'd say this is clearly a bug in default implementation.

**Comment by pennersr** [comment]
While I agree that the documentation is indeed lacking in various areas, I am adhering to the debatable principle that keeping open issues around with respect to documentation is not very helpful in improving things. Feel free to submit a pull request...

**Comment by velis74** [comment]
I agree with you. But my point was that I'm unable to find information that would lead me to an operational setup. I'd gladly fix the documentation and submit a pull request if I found a solution. I did not. And I tried really hard, spent a whole day browsing through StackOverflow answers, google search results and other documents / tutorials that I could find.

Point 1 and 4 of issue are code, not documentation bugs. Put in other words: the example app doesn't work on Python 3.4 Django 1.8 allauth 0.23.

They are the reason why I submitted this as a bug. I guess I just hoped someone knowledgeable about the module would take a look and fix the example so that it would work with Django 1.8. THEN would I be able to see the difference and fix the documentation.

Sorry if this is not something you want to discuss any more. Just close again if that's the case.

**Comment by carltongibson** [comment]
`accounts/profile/` is the default "redirect after login" location. You're meant to implement it or adjust `settings.LOGIN_REDIRECT_URL` [Link to the docs](https://docs.djangoproject.com/en/1.8/ref/settings/#login-redirect-url)

The login page styling and Django Admin or Rest Framework integration really are beyond AllAuth's scope — there's nothing _social_ about either of those.  

So it comes down to the configuration of your Google login... from my own experience I'd say if >90% likely you've got a config issue, most likely on the Google side — where it's not the easiest thing to set up right. 

If you're looking for help **here** you need to provide very detailed information that gives us something to work with. 

First thing is to check your config. If you can explain how the issue is occurring we may be able to help. 

Did you see the "missing AllAuth tutorial" article — which is still good? Can get it working with another provider? (Google isn't the simplest to set up correctly.)

I hope that helps.

**Comment by pennersr** [comment]
To address the bullets you mentioned:

1) The example won't work without proper credentials. And even then it is very easy to run into issues: some providers won't accept port 8000 in callback urls, others refuse localhost but do accept 127.0.0.1, sometimes people make mistakes in copying the credentials. All in all, I am certain the issue you are running into here is not due to a bug in allot, but do the misconfiguration. What exactly is misconfigured I cannot tell...

2) Replacing the admin login is not something in scope for allauth. 

3) Intentional, indeed

4) The URL you end up after logging in is just the Django default (see https://docs.djangoproject.com/en/1.8/ref/settings/#login-redirect-url). It's not something allauth implements for you, you'll have to do that yourself as this goes beyond the scope of authentication.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1129
