### ISSUE TITLE
ACCOUNT_EMAIL_VERIFICATION="mandatory" does not work well

### ISSUE THREAD

**Issue by dolgidmi** [pennersr/django-allauth#1208]
Version: 0.24.1
Configuration:
```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = False
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_REQUIRED = True
```
I am using a LinkedIn_oauth2 provider.
If I try to use LinkedIn account to create a new account, then there is no email verification. It is ok.

If I try to sign in via LinkedIn account which have the same email as an existing local account, I will get redirect to `/accounts/social/signup/` with SignupForm which is also correct.
BUT If I use this form to create account with another email, there is no email verification as well.

So, this form allow to skip email verification and connect an existing LinkedIn account to the new local account with another email. 
Why it does not use ACCOUNT_EMAIL_VERIFICATION instead of SOCIALACCOUNT_EMAIL_VERIFICATION?

**Comment by pennersr** [comment]
Requiring email verification is a means to gain confidence that the user will be able to access his account at any time, either by following the password reset procedure or by using a social account provider. In case of the password reset case, it is important that his email is valid and verified, otherwise the user will be locked out. In case a social account is attached, password reset is not essential, as a 2nd means of gaining access to the account exists: the social provider.

Your configuration requires that the user 1) verifies his local account by doing email verification, or 2) that he signs up using a social account. The latter is exactly what happens in your use case. Email verification does not kick in because a social account was used. So in that sense allauth is working as expected.

Note that even though email verification does not kick in, the email address is not marked as verified.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1208
