### ISSUE TITLE
BaseSignupForm  overrides field_order of custom signup form

### ISSUE THREAD

**Issue by graup** [pennersr/django-allauth#1226]
If I am not mistaken, the BaseSignupForm [overrides any `field_order`](https://github.com/pennersr/django-allauth/blob/9d8ab54de5eaa12eff2964ff5c994ac3ffed1dcd/allauth/account/forms.py#L226-L246) that one could have defined in the custom base form via `ACCOUNT_SIGNUP_FORM_CLASS`.

In our use case, we used a custom form to add additional fields, however we cannot affect the order of those, which is especially annoying with the `password` fields which always appear at the end.

My proposal is that BaseSignupForm should check if `field_order` is defined and if so only add additional fields if not previously defined.

If this makes sense I would happily provide a PR with test and fix.

**Comment by graup** [comment]
I should mention I am talking about compatibility with a new Django feature here, [`field_order` introduced in 1.9](https://docs.djangoproject.com/en/1.9/ref/forms/api/#django.forms.Form.field_order)

**Comment by BertrandBordage** [comment]
:+1:

**Comment by BertrandBordage** [comment]
A workaround is to define two fields 'password1' & 'password2', then mention them in `Meta.fields`.

**Comment by ClemLivy** [comment]
Same issue for me...

I'm working on django 1.10

I configured my form to have two emails field for confirmation, one password.

```
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_SIGNUP_EMAIL_ENTER_TWICE = True
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False
```

 I also add to some custom fields in a custom SignupForm class : first_name, last_name, birth_date, gender

In my SignupForm class I add
`field_order = ['first_name', 'last_name', 'email', 'email2', 'password1', 'birth_date','gender' ]`

Everything works fine except the email2 field that appears at the end...

Do you have a trick for that?

**Comment by amadornimbis** [comment]
@ClemLivy 
>Everything works fine except the email2 field that appears at the end

This is because the email2 field is added to the form in the `__init__` function of BaseSignupForm: https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L257

A similar thing happens now in v0.31.0 where you can't modify the order of the `password1` and `password2` fields using `field_order` (in Django 1.9+) because the these fields were moved to the __init__ function of SignupForm as part of [this commit](https://github.com/pennersr/django-allauth/commit/882030ced0584457448bdcf548a6c482fd66a827).

@pennersr What is the prescribed way to change the order in which these fields appear in a custom form that you point to using the `ACCOUNT_SIGNUP_FORM_CLASS` setting?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1226
