### ISSUE TITLE
How to properly handle merge of two accounts by social login?

### ISSUE THREAD

**Issue by darklow** [pennersr/django-allauth#1264]
Could somehow suggest some directions in how to properly merge two user accounts if user created two separate accounts by first logging in by for example Twitter, then logging out and then logging in with Facebook and realising we created new profile and his collected data is lost.

Now there is no way user can add previously created Twitter account to currently created Facebook account or vice versa. User now gets error message: "The social account is already connected to a different account."

Instead after the same error I would like to offer user extra option - "Would you like to merge account you are connecting into current one?" If user has access to same social account that already exists, it is pretty obvious it is same user. And afterwards manually merge all the collected/related to user data into single account. 

Looks like my problem is similar to this issue:
https://github.com/pennersr/django-allauth/issues/277

Since error is managed in helper, i can't use adapters either.
https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L103
In the same method i already have all instances i need to perform merge: `sociallogin.user`, current `request.user` and `sociallogin`.

Any suggestions, where could i hook in to handle this case?
Where to start looking for, how do you handle this?
Thank you

**Comment by pennersr** [comment]
This is something that allauth is not able to handle out of the box. If the user accidentally created two accounts, merging them requires project level knowledge. For example, suppose you have a project where users can comment, and the user already made use of that functionality two comment using both accounts. In that case, you would want to switch the `user` foreign key of one of the `Comment` records.  

In order to merge two accounts the user should exhibit proof of ownership of both of the accounts. So, you definitely need some extra UI for that, allowing the user to login while already being logged in.  Choices made here are likely not suitable for every project.

All in all, I don't consider this to be in scope for allauth. You can already hook into the `pre_social_login` and check if you are on a collision course, and if so, inject your own logic (e.g. by raising a `ImmediateHttpResponse`). For now, I don't want to offer more than that...

**Comment by darklow** [comment]
Thank you, your comment is exactly what I was looking for. I don't want this to be included in the allauth app, i was looking for advice on how to do it proper way, so i don't have to fork and customise or monkey patch. Using ImmediateHttpResponse and cloning last part of `complete_social_login()` would work for me.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1264
