### ISSUE TITLE
Verify email during password reset

### ISSUE THREAD

**Issue by tkwon** [pennersr/django-allauth#1267]
I created a new user (without verifying email) and used the forgot password link. Upon submission of my new password, I'm sent to the resend activation view. Shouldn't I be logged in?
Here's the views I have to go through:
1. reset password link
2. enter new password form
3. resend activation email form
4. logged in after clicking link

If this is the expected behavior, how can I correct it so user is logged in after resetting password. By receiving the reset password link he has confirmed his email.

I'm using 0.24.1 with the following settings:

ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_FORMS = {
    'login': 'registration.forms.LoginForm',
    'signup': 'registration.forms.SignupForm',
    'reset_password': 'registration.forms.ResetPasswordForm',
    'reset_password_from_key': 'registration.forms.ResetPasswordKeyForm',
}
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGIN_ON_PASSWORD_RESET = True
ACCOUNT_ADAPTER = 'registration.adapter.AccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = 'optional'

**Comment by pennersr** [comment]
allauth does not store the email address to which the password reset mail was sent. In fact, it does not store any data... only a user ID is encoded in the password reset token. So, considering that users can have multiple email addresses we have no way of knowing which once was verified. One way around this would be to put the EmailAddress id in the token...

**Comment by derek-adair** [comment]
Is it worth putting the EmailAddress id in the token?  Would this be a security risk? _(probably not just asking)_

Seems like something that I would personally not do but welcome a PR from anyone who found this important.  Likely much bigger fish to fry for the ROI.

**Comment by pennersr** [comment]
Random thoughts:

- Email verification is always a bit of a hassle, and if we can skip verification because we already did so via the password reset, that would result in a UX improvement.
- I don't see a security risk in adding the email address ID to the token, other than the fact that somebody can make an educated guess on how many users a site has based on the ID. But, that is a different issue that is to be tackled by not using integer based PKs.
- At what stage would you mark the email as verified? When you GET the password reset page? How would that relate to `ACCOUNT_CONFIRM_EMAIL_ON_GET`.
- Email verification normally is accompanied by messages (`account/messages/email_confirmed.txt`). Would we need to silence those, as the user is not really aware he is verifying the email address.
- Given that the user is not aware this is happening -- is it really a UX improvement?

**Comment by pennersr** [comment]
Moved to https://codeberg.org/allauth/django-allauth/issues/1267

**Comment by pennersr** [comment]
This is supported when `ACCOUNT_PASSWORD_RESET_BY_CODE_ENABLED` is `True`.
