### ISSUE TITLE
Logic behind "mandatory" and is_active in ACCOUNT_EMAIL_VERIFICATION

### ISSUE THREAD

**Issue by rserrano** [pennersr/django-allauth#1313]
I can't seem to grasp the logic on this one. Mandatory does not set the is_active flag to False in the user, but when I capture the signal to set it with the following code:

```
@receiver(user_signed_up)
def signing_up(request, user, **kwargs):
    user.is_active = False
    user.save()

```
Then it does not send a verification e-mail. Like why? What's the big logic behind it? Why are you checking for the is_active flag in perform_login before sending the e-mail?
```

def perform_login(request, user, email_verification,
                  redirect_url=None, signal_kwargs=None,
                  signup=False):
    """
    Keyword arguments:
    signup -- Indicates whether or not sending the
    email is essential (during signup), or if it can be skipped (e.g. in
    case email verification is optional and we are only logging in).
    """
    # Local users are stopped due to form validation checking
    # is_active, yet, adapter methods could toy with is_active in a
    # user_signed_up signal. Furthermore, social users should be
    # stopped anyway.
    if not user.is_active:
        return HttpResponseRedirect(reverse('account_inactive'))

```
Why?

This is driving me crazy.

**Comment by pennersr** [comment]
allauth intentionally stays away from the `is_active` flag. It only reads it and blocks users from logging in, and never writes to it. The reason is that `is_active` is fully under your control, e.g. to disable the account of users that are spamming or did not pay. Whether a user has confirmed his email is derived from the `EmailAddress` model (see the `verified` property).

**Comment by fproldan** [comment]
@rserrano  Hi, how do you manage to solve this? I need the users verify the email and also be created with is_active=False (due every new user need to be reviewed and approved by admin users that manually activate it).
If I add is_active=False in the signal or custom ModelForm the verification email isn't sent.
Thanks!

**Comment by anuj9196** [comment]
I need it too. I'm also searching to implement the same logic as of @fproldan . Please provide a documentation on how to create an account with `is_active=False` and let user verify his email address in order to activate the account. 

I can manually set `is_active` field status by listening to the signals, but what about email send and confirmation.

In my application, User will have only one email.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1313
