### ISSUE TITLE
Social login incompatible with i18n sites

### ISSUE THREAD

**Issue by fonar** [pennersr/django-allauth#1330]
If we have oauth2 callback like:

http://example.com/accounts/provider/login/callback/

when using multilanguage site, allauth sets callback like

http://example.com/en/accounts/provider/login/callback/

which cause to login failure.

I think in
`allauth.socialaccount.providers.oauth2.views.OAuth2View.get_client`
code
`callback_url = reverse(self.adapter.provider_id + "_callback")`
must be something like
`callback_url = reverse_no_i18n(self.adapter.provider_id + "_callback")`
with implemented `reverse_no_i18n` function

**Comment by pennersr** [comment]
I am not sure what mechanism you are using for multilingual URLs. But, if you are using Django `i18n_patterns` and make sure that the allauth URLs are not included as part of that, then you should be fine.

**Comment by 29axe** [comment]
I'm facing the same issue. 
Using i18n_patterns uses the url: localhost:8000/en/accounts/x/y/z but the callback url is then not working with social provider (or you have to add all languages as callback urls). 
What you suggest works but it goes against the i18n

**Comment by eillarra** [comment]
@pennersr maybe it will be interesting to separate the allauth urls in two groups: the ones that could use i18n (login, password_reset, signup, etc.) and the ones that are exclusively used for oauth authentication.

If we add all urls with i18n_patterns then we need to add multiple ouath callback urls in Facebook, Twitter, Google... and that makes it more difficult to maintain when lots of languages are involved.

**Comment by frankyhung93** [comment]
Agree with @eillarra , am facing the same issue here.

**Comment by Ajordat** [comment]
Just in case it could be helpful to someone, I came up with a workaround, albeit it does have flaws. As stated here, the issue is that the callback URIs also have the language code inserted in the URL if they're part of the `i18n_patterns`, but currently there's no way to separate it into two groups as stated by @eillarra -which would resolve the issue.

So in this case:

```python
urlpatterns += i18n_patterns(
    path("accounts/", include("allauth.urls"))
)
```
When inspecting the URLs we find that they're all under `/en/accounts/`

Basically, the workaround consists of doing the heavy lifting of building allauth's urlpatterns ourselves instead of directly importing the [urls file][1].

```python
urlpatterns = [
    path("accounts/", include("allauth.socialaccount.providers.github.urls"))
]
urlpatterns += i18n_patterns(
    path("accounts/", include("allauth.account.urls")),
    path("accounts/", include("allauth.socialaccount.urls"))
)
```
With this setup, all the provider urls will be under `/accounts/` and the rest, under `/en/accounts/`.

This has advantages and disadvantages, so consider it well before making this change.

### Advantages

* It's an easy way to have all regular auth views translated to different languages.
* Social providers will work as the callback URI will be correctly used.

### Disadvantages

* More setup that simply including all URLs with a single path.
* Requires knowing what paths to include. It's relatively easy by using [django-extensions'][2] `show_urls` command and the [urls file][1].
* Every provider has to be included manually to the `urlpatterns`.
* The social login will not be translated and will be served under the default language. That happens because the login URL is returned as part of the provider's URLs, which does not have the language code. Ideally we would want that page to also be translated.
* Updates on the library will require to pay attention to the defined urlpatterns of allauth to ensure nothing is left behind.

### Conclusion

This workaround has more advantages that disadvantages, but at least provides for a quick remedy if someone else is facing this issue.
The two solutions I can think of are:
* that we could retrieve the urlpatterns separately for every allauth URI and the social callbacks. But breaking with Django's habitual `include` pattern is undesirable in my opinion.
* Or that a second file exists and provides a i18n solution such as that we could do: `path("accounts/", include("allauth.urls_i18n"))` into `urlpatterns` directly.

I'm unaware of the feasibility of either solution, but it'd be great if @pennersr could chime in on how to tackle i18n and the callback URIs for social providers.

[1]: https://github.com/pennersr/django-allauth/blob/main/allauth/urls.py
[2]: https://github.com/django-extensions/django-extensions

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1330
