### ISSUE TITLE
django templates string_if_invalid breaks links to providers

### ISSUE THREAD

**Issue by patroqueeet** [pennersr/django-allauth#1427]
Dear,

when I enable this setting:
`TEMPLATES[0]['OPTIONS']['string_if_invalid'] = 'INVALID_VAR'`

the links in the `account_signup` view to the providers look like:

```
http://codingmachine2.local:8000/accounts/twitter/login/?process=login&scope=INVALID_VAR&auth_params=INVALID_VAR
http://codingmachine2.local:8000/accounts/google/login/?process=login&scope=INVALID_VAR&auth_params=INVALID_VAR
http://codingmachine2.local:8000/accounts/facebook/login/?process=login&scope=INVALID_VAR&auth_params=INVALID_VAR
```

for now I disabled this setting, but would love to get it back as I like to know where missing data is not handled properly...

**Comment by derek-adair** [comment]
Vote to close / won't fix.   The user has not mentioned what they expect the behavior to be so I cannot speak to if this is even valid but it seems like it's possible this user just doesn't know what the 'string_if_invalid' setting is.  The user can very easily just have invalid variables -- this is the expected behavior if he is supplying invalid variables.

**Comment by pennersr** [comment]
See:

https://docs.djangoproject.com/en/4.2/ref/templates/api/#invalid-template-variables

Particularly:

> For debug purposes only!

and

> Many templates, including some of Django’s, rely upon the silence of the template system when a nonexistent variable is encountered.

Won't fix this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1427
