### ISSUE TITLE
Email Verification Link Invalidation

### ISSUE THREAD

**Issue by last-partizan** [pennersr/django-allauth#1522]
If user uses same link again within `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS` it should not be working.

Possible fix for `EmailConfirmationHMAC`: use not only EmailAddress.pk, but pk and verified flag. So key is invalidated if email confirmed.

**Comment by 9mido** [comment]
Similar to #2731

**Comment by gabn88** [comment]
Subscribing to this topic. 
In my flow, blacklisting email verification links is mandatory. This is because admin users in an organisation can create new users for their organisation (with an emailaddress). But they can also change the email-address afterwards if the user hasn't logged in yet (for example if they had a typo in the mailaddress). But let's say the emailaddress with the typo really exists, that user can use the email confirmation link to create a password for the user account and change the emailaddress to something they want.

**Comment by 9mido** [comment]
For the signup confirmation links to 'appear' be expired immediately after the user confirms their email address, you can do this:

https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py:

```
class ConfirmEmailView(TemplateResponseMixin, LogoutFunctionalityMixin, View):

    template_name = "account/email_confirm." + app_settings.TEMPLATE_EXTENSION

    def get(self, *args, **kwargs):
        try:
            self.object = self.get_object()
            if app_settings.CONFIRM_EMAIL_ON_GET:
                return self.post(*args, **kwargs)
            email = self.object.email_address.email
            if EmailAddress.objects.filter(email=email, verified=True).exists():
                raise Http404
        except Http404:
            self.object = None
        ctx = self.get_context_data()
        return self.render_to_response(ctx)
```

I say 'appear' because they are not truly expired until the ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS runs out. It would be better to just run a piece of code that forces the expiration of the links as if ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS runs out. In other words, figure out how to make a link that expires immediately after clicking it inside of the email provider inbox. If anyone here can figure that out, please share. Maybe that can be a separate allauth setting. But then again, if a user accidentally closes the one time link, they cannot access that link again which may be a bad idea. So I guess this approach is a happy middle ground. 

With the method above, users can confirm their email, and they cannot use the same verification link or do anything with that link again after confirming. They can keep using the same link over and over again if they are not verified until ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS expires.

**Comment by derek-adair** [comment]
+1 if this is not already fixed in some way.  I haven't looked at the email verification code in some time so I am completely ignorant of the state of this.

**Comment by pennersr** [comment]
This is done.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1522
