### ISSUE TITLE
Error with connection with vimeo

### ISSUE THREAD

**Issue by politoxela** [pennersr/django-allauth#1572]
Hi!
I love django-allauth has helped me in several projects to connect social networks.

I am currently working with the integration of vimeo to my project, but at the moment of making the connection this indicates to me that it could not be done and does not tell me what the error is specifically.

Reviewing the django-allauth documentation does not specify a redirect url as with other social networks. Also within the configuration reviewing the source code I can realize that currently the authorization address is the following: 'https://vimeo.com/oauth/authorize' but in vimeo it is specified that it should be the following address' https://api.vimeo.com/oauth/authorize '.
What should I do to make me work vimeo?

**Comment by bittner** [comment]
I have Vimeo working on the [Organice Demo](https://demo.organice.io/login) site. The website is rebuilt every morning. You can take a look at the [management commands](https://github.com/Organice/django-organice/blob/master/organice/management/commands/mixins/initauth.py#L48) that set up the social accounts.

My [Vimeo app](https://developer.vimeo.com/apps) doesn't even have a valid callback URL (it's `https://demo.organice.io` for both, OAuth and OAuth2). Though, maybe it works just because I created that app quite a while ago -- just guessing.

Look Closely
----------
If you really think, it "does not tell me what the error is specifically", look at the address bar of your browser. Some services add the error message to the URL (as a query parameter of the GET request) when doing the callback. Try logging in with "SoundCloud" on [Organice Demo](https://demo.organice.io/login) to see a demo of such a behavior.

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by politoxela** [comment]
Thanks for the answer, I will check my code again and what changes you need to make it work properly, Regards.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1572
