### ISSUE TITLE
Password change view doesn't have a sucess indicator

### ISSUE THREAD

**Issue by tasn** [pennersr/django-allauth#1608]
Hey,

The view account_change_password, while works, has no way to indicate to the user that a password has changed successfully. It either shows an empty form or an error form.

Way to reproduce:
1. Change password
2. See there's no visual feedback other than "no error message", but that looks exactly like a how a refresh would look.

We need a variable or a way (transition to another page?) to indicate that a password has been set correctly.

Thanks,
Tom

**Comment by pennersr** [comment]
It does have an indicator, it uses the messages framework to emit a "password successfuly changed" notification to the user.

**Comment by tasn** [comment]
Sorry, I meant immediate feedback.

After a successful password change, the page you get to is just the same password change page, not a success page, and there's way to change that behaviour (e.g "next" in the url).

**Comment by DanAtShenTech** [comment]
Since allauth uses the messages framework, then if you render messages in the usual manner, you get all messages that have not yet been rendered.  @pennersr Since the messages framework is the chosen method of passing the confirmation message back for rendering, then it seems like the messages queue should be cleared before adding the confirmation message (or at least make clearing the queue an option to allow the developer to specify whether to clear all messages before adding a new one).  Otherwise we can end up with a number of messages that are irrelevant to changing the password.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1608
