### ISSUE TITLE
0.31.0 breaks customized Signup Forms

### ISSUE THREAD

**Issue by falc410** [pennersr/django-allauth#1699]
Please see my comments to Issue https://github.com/pennersr/django-allauth/issues/1698 - I can confirm that it is related to 0.31.0 (all versions before work fine). 

The solution from 2015 which was explained in Issue https://github.com/pennersr/django-allauth/issues/826 no longer works.

**Comment by pennersr** [comment]
The solution in #826 still works, and the referenced example over at stackoverflow (http://stackoverflow.com/a/12308807/593944) is still sound. As  indicated over at #1698, your issue is not that the custom signup form is not working, your issue is that addressing fields that are not part of your custom signup form no longer works.  

Now, it may be the case that addressing the password fields may have worked, but that is never the way this was supposed to work. Given that your custom signup form inherits from just`forms.Form` it should not have access to the password fields in its `__init__`.  Note that Django internals have also changed on this point (e.g. dropping keyOrder and so on), so this may also explain the change in behavior. 

In any case, this is not a bug. If you need to alter the complete signup form, use ACCOUNT_FORMS.

**Comment by falc410** [comment]
Just in case someone else finds this using Google, the solution was rather simple.
In settings.py do this
> #ACCOUNT_SIGNUP_FORM_CLASS = 'play.forms.SignupForm'
ACCOUNT_FORMS = {'signup': 'play.forms.CustomSignupForm'}

and your form which was previously something like:
>class SignupForm(forms.Form):

change it to:
>from allauth.account.forms import SignupForm
class CustomSignupForm(SignupForm):

Then it works with 0.31.0 again (and Django 1.10, the original code for this Form was written in Django 1.7)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1699
