### ISSUE TITLE
Different users per different sites

### ISSUE THREAD

**Issue by biggosh** [pennersr/django-allauth#1728]
Hello.

I need to grant different users to the application for different sites.
I read that is already possible to have different social apps for different site, is it possible to check the user validity based on the site the user is accessing?

Thanks
CF

**Comment by pennersr** [comment]
You can have different social apps per site. But I don't think that helps you out here. What you are actually after is a custom user model with a foreign key to the site the user belongs to. I don't think there is anything in allauth that prevents you from setting this up, so I am closing this.

**Comment by radyz** [comment]
I'd like to implement this feature as well however I'm stuck due to the constraints set on the EmailAddress model:

1. If I set UNIQUE_EMAIL = True then a constraint on the email field is set
2. If I set UNIQUE_EMAIL = False then a constraint on user + email is set

Either way I'm then unable to create users with the same email for different sites, otherwise I could have user_1 register for site_1 but that user won't be able to create a "new" account on site_2 because his/her email is already being used in site_1.

**Comment by radyz** [comment]
Nevermind my comment above, I just realized the constraint is over the user fk and not the username. I can accomplish this with a fk to the site's model from my custom user model.

**Comment by bodgerbarnett** [comment]
@radyz Were you trying to do this while using the user's email address as their login or are your users using a username to log in?

I'm trying to allow the same email address to be used to create different accounts on 2 different sites but I can't work out what settings I need to make it work.

I have an FK to the site in my custom user model but because I'm using email as username, I have to keep UNIQUE_EMAIL set to True or line 25 of https://github.com/pennersr/django-allauth/blob/master/allauth/account/app_settings.py breaks me.

Any ideas?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1728
