### ISSUE TITLE
issue with wagtail

### ISSUE THREAD

**Issue by kakulukia** [pennersr/django-allauth#1847]
not sure of whom to blame here (probably wagtail), but allauth tries to get the current Site using djangos site model which produces a DoesNotExist exception .. somehow poeple manages to get it still working side by side, but so far i have not figured out how .. couldsomebody show me how its done?
So far i have listed django sites and all allauth installed apps last .. dindt work :(

**Comment by pjmcdermott** [comment]
This is because the Wagtail site middleware sets the `request.site` variable, which is the same thing the Django site middleware does. Wagtail is incompatible with any Django app that attempts to use the Django sites framework, including `allauth`. This is a Wagtail issue see [Wagtail Issue 2840](https://github.com/wagtail/wagtail/issues/2840)

**Comment by kakulukia** [comment]
Okay, i see .. so this is to blame on wagtail and does not belong here.

**Comment by pcdummy** [comment]
For others looking to integrate these two:

django.contrib.sites and wagtail are no more incompatible with each other: https://github.com/wagtail/wagtail/pull/5787

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1847
