### ISSUE TITLE
Ill encoded character in 4 .po files

### ISSUE THREAD

**Issue by P-EB** [pennersr/django-allauth#1910]
Hi !

We realized while packaging django-allauth into debian that some .po files contain an ill-encoded character:

https://github.com/pennersr/django-allauth/blob/master/allauth/locale/es/LC_MESSAGES/django.po#L12
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/tr/LC_MESSAGES/django.po#L13
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/pt_PT/LC_MESSAGES/django.po#L12
https://github.com/pennersr/django-allauth/blob/master/allauth/locale/sv/LC_MESSAGES/django.po#L12

We designed a patch for the Debian's package but this might be interesting to fix in your own repository.

https://anonscm.debian.org/cgit/python-modules/packages/django-allauth.git/commit/?id=16c4b76a9af1993aa110a894388cd80a9780b1e0

Thanks!

**Comment by larjona** [comment]
Hello
My request to join the django-allauth translation team in Transifex has been approved and I've been able to check the affected .po files in Transifex. All of them now have an updated "Last translator" or the name of the translator with no bad encoding character. So instead of merging my pull request, updating the git repo retrieving the last translation from Transifex would fix the issue too.
I will close my merge request now.

Thanks!

**Comment by P-EB** [comment]
Right, I'll close this issue, too.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1910
