### ISSUE TITLE
django-allauth compatibility

### ISSUE THREAD

**Issue by fundacjafanimani** [pennersr/django-allauth#1925]
For me `django-axes` didn't work with `django-allauth` package by default.
After some digging in code I've made my own `apps.py` that monkey patches allauth's `LoginView` the same way as axes does it to django's `LoginView`:
```
class AppConfig(apps.AppConfig):
    name = 'my_app_name'

    def ready(self):
        from allauth.account.views import LoginView  # <-- Just this line is changed
        from django.utils.decorators import method_decorator

        from axes import signals    # we must load signals
        from axes.decorators import axes_dispatch
        from axes.decorators import axes_form_invalid

        LoginView.dispatch = method_decorator(axes_dispatch)(LoginView.dispatch)
        LoginView.form_invalid = method_decorator(axes_form_invalid)(LoginView.form_invalid)
```

It may be useful to either point that out in readme or to modify `apps.py` to try to detect allauth and patch it too.

I'm using:
django-axes==4.0.1
django-allauth==0.34.0 (note: 0.31.0 didn't work with my fix either, had to upgrade)
django==1.11

**Comment by pennersr** [comment]
The issue description is not clear to me. So, axes does not work with allauth, that part I get. But, what is not clear to me is what the issue in allauth is, if any, that is causing this. So instead of saying project X does not work with allauth I would like issues to be rephrased as pointing to allauth specific issues. Without this information I will have to close this issue.

**Comment by fundacjafanimani** [comment]
Sorry, mistake! This was supposed to go to django-axes issues, not yours. 
Closing.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1925
