### ISSUE TITLE
Change email doesn't give feedback when trying to make unverified email primary

### ISSUE THREAD

**Issue by invertium** [pennersr/django-allauth#1958]
https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/email.html

When trying to make an unverified email address primary, the page reloads. There should be a way to tell the user he has to verify it first.

**Comment by derek-adair** [comment]
I'm a bit confused here.  This is potentially a valid feature but it's not clear what the user expects to happen vs what is actually happening.

The user needs to provide;

1. Their allauth version / relevant configuration.  Specifically if verification is required.
2. Their expected behavior.

I _THINK_ they are saying that when VERIFICATION is required and the user hasn't verified there is no error message.  I will look into this one when I have a moment next week sometime.

**Comment by derek-adair** [comment]
One of the things you should do to help coach users to submit valid issues is to set up some [issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by pennersr** [comment]
Closing, dated. You do get a proper "Your` primary email address must be verified." message in this case.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/1958
