### ISSUE TITLE
Some pages are accessible, which shouldn't be.

### ISSUE THREAD

**Issue by satyakampandya11** [pennersr/django-allauth#2010]
Hello,
I noticed one issue here, there are some urls which should be only accessible if user passes first step, such as, password/reset/done/ shouldn't be accessible unless user has passed first step, that is to submit correct email address.

**Comment by gajeshbhat** [comment]
You can add a custom redirect using javascript in your HTML template. You can also override the `PasswordResetDoneView` to change the view altogether. But this will also affect the view behavior when the password reset email is sent.
Reference :
1. The View: https://github.com/pennersr/django-allauth/blob/master/allauth/account/views.py#L662
2. The urls .py: https://github.com/pennersr/django-allauth/blob/master/allauth/account/urls.py#L27

**Comment by pennersr** [comment]
Not sure this is worth changing. Yes, you can view the done view, but what harm is there to that? Using a redirect instead of returning a page directly on the post is good practice. At least the current approach avoids reposting forms when users would refresh the success page (or use the back button).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2010
