### ISSUE TITLE
Django message upon logout is confusing to users

### ISSUE THREAD

**Issue by shacker** [pennersr/django-allauth#2031]
allauth generates a Django message upon logout, which is not displayed on the following page, since ... the user has logged out. The message is stored by Django until the next time user logs in, when they are told "You have logged out" followed by "You have logged in." This is confusing to the user.

I am able to suppress this by copying the logged_out.txt template and blanking it, but I think allauth probably shouldn't generate a Django message on logout to begin with.

**Comment by gajeshbhat** [comment]
You can resolve this issue by loading the message tag in the page to which the logout redirects. I assume its login here. You can define the message tag in your `base.html` and extend wherever it's required.
To give you a simpler explanation. Consider the messages generated as cards in which are put in a box. Whenever you extend the message tag in a page, the box is emptied. So it's better to place these in the page where you know messages will be displayed. I prefer to put them in `base.html` so that they can be extended anywhere they want.
A simple example: in `base.html`
```
<html>
<head>
</head>
<body>
{% block messages %}
{% endblock %}
</body>
</html>
```
In any page where you want the messages, lets say home.html` (I have used Bootstrap-4 styles)
```
 {% block messages %}
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                  <strong>{{message}}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
        </div>
        {% endfor %}
    {% endif %}
  {% endblock %}
```

**Comment by shacker** [comment]
@gajeshbhat D'oh! I was going on the assumption that messages could not be displayed to a user who has logged out, but of course django messages work for unauthenticated users as well. I hadn't included a `messages` block on the login page to which a logged-out user is redirected because I assumed it wouldn't work.  D'oh! In that case, I rescind this issue. Thanks. :)

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2031
