### ISSUE TITLE
Changing ACCOUNT_UNIQUE_EMAIL attribute from True to False doesn't reflect the changes in Postgres DB.

### ISSUE THREAD

**Issue by SherMarri** [pennersr/django-allauth#2041]
Previous configuration of my app was the following:
```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_AUTHENTICATION_METHOD = "email"
```
And the Custom User Model for the above configuration:
```
class User(AbstractBaseUser):
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, unique=True)
```
Then I had to change the **ACCOUNT_AUTHENTICATION_METHOD** to **username**, so I updated configuration as following:
```
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = False
ACCOUNT_AUTHENTICATION_METHOD = "username"
```
And the changed the Custom User Model to:
```
class User(AbstractBaseUser):
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(max_length=255, unique=False)
    username = models.TextField(max_length=255, unique=True)
```
I performed the migration after deleting all the users and changing the user model , but I was still not able to register user with same email address, it returned Duplicate Constraint error. I found that it was an error from Postgres. As I looked deeper, I checked the DDL of EmailAddress table where I found the Unique constraint on 'email was still there and an Index was also there for 'email' field. As a quick fix, I manually removed these constraints, however, I think its either a problem with allauth or I missed something. Please clarify.

**Comment by amazingguni** [comment]
@SherMarri 

I got the same problem and found the reason and solution.

The problem is that ACCOUNT_UNIQUE_EMAIL is only referenced in db migration time. 
https://github.com/pennersr/django-allauth/blob/f0c1defd5c4bbe33ab8eb9d5811d9b16f726b73e/allauth/account/models.py#L23
https://github.com/pennersr/django-allauth/blob/41f84f5530b75431cfd4cf2b89cd805ced009e7d/allauth/account/migrations/0002_email_max_length.py

If you change the options after running `python manage.py migrate` once, it will not take effect. 
So I would recommend going directly to db to get rid of constrant.
example psql query: https://gist.github.com/amazingguni/d0f44da197eb2f93e134fa43dad5fab0

**Comment by kayesh** [comment]
How to run the psql ? Which tool to use ?

**Comment by pennersr** [comment]
This is by design. The settings influence the behavior of the migrations. You cannot alter the settings on a system that is already fully migrated without taking special/manual care.

**Comment by sebhaase** [comment]
Could this be mentioned in the documentation anywhere?
Also: what are the manual commands to remove the constraint? In psql ... (is this also required for sqlite?). And: how about the index? That must also be removed, right? How?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2041
