### ISSUE TITLE
Compatibility with Django 2.1

### ISSUE THREAD

**Issue by tobiasgoecke** [pennersr/django-allauth#2082]
As of version 2.1, django-allauth raises

TypeError allauth.account.adapter in is_safe_url
erroris_safe_url() missing 1 required positional argument: 'allowed_hosts'

From the 2.1 release notes:

allowed_hosts is now a required argument of private API django.utils.http.is_safe_url()

**Comment by cvipul** [comment]
I am getting this error when a user tries to log out..
Is this solved in the latest versions of django-allauth? I could not find anything related to this in the release notes.
@tobiasgoecke - Why was this closed?

**Comment by J-Kowalski** [comment]
I was getting the same error and then stumbled across this issue. Despite also not being able to find anything in the release notes, I believe it was fixed in version 0.36.0 with this commit: https://github.com/pennersr/django-allauth/commit/96cf384c272bed81c4368ac50d2e02bd5a79399f

Upgrading to the current latest (0.39.1) solved this issue for me

**Comment by tobiasgoecke** [comment]
as @J-Kowalski mentioned

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2082
