### ISSUE TITLE
[Transifex] Include Basque locale

### ISSUE THREAD

**Issue by eillarra** [pennersr/django-allauth#2085]
This is not really an issue.

Could you please check a language request I made 3 months ago in [Transifex](https://www.transifex.com/user/profile/eillarra/) for Basque (eu)? There is no way to contact the team via the Transifex website, so I'll use this issue to ping 👆 the _django-allauth_ team.

**Comment by ctrl-alt-d** [comment]
I just posted [here](https://pastebin.com/QSDWdRkM) the [catalan](https://en.wikipedia.org/wiki/Catalan_language) messages because catalan is not enabled on Transifex.

Meantime, as workaround, [I have created my own 'locale' folder on my project and add it to settings](https://stackoverflow.com/a/52004442/842935).

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2085
