### ISSUE TITLE
Response of /password/change when posted via AJAX

### ISSUE THREAD

**Issue by doganmeh** [pennersr/django-allauth#2098]
When a valid data is posted to /password/change via AJAX, I get the following response:

```
{
location: "/accounts/password/change/",
form: {...},
html: ""
}
```
namely, it posts the form back in JSON, however, `html` content is empty. Is this normal behavior? I would expect, like in non-AJAX response, a success message followed by the form in `html` as well.

**Comment by iarp** [comment]
html would be blank because the default for that view is to redirect to `account_change_password` on success. Preventing the user from refresh double submitting by accident. Redirects typically have no body only a header indicating where to go next.

As for messages those could be disabled by using your own account adapter and overriding `add_message` method with your own logic.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2098
