### ISSUE TITLE
Custom Signup Form when inheriting from SignupForm instead of UserCreationForm

### ISSUE THREAD

**Issue by raceybe** [pennersr/django-allauth#2237]
When using a custom signup form while inheriting from SignupForm, I have noticed that I am unable to specify the desired form fields using the `fields=('field1','field2',)` etc notation in the class Meta. If I inherit from Django's `UserCreationForm`, then the desired fields appear just fine and show up on the form when rendered.

Is this a bug or a desired property of the SignupForm hierarchy?

**Comment by derek-adair** [comment]
Bah! Not enough details here; It is unclear if the user is specifying a custom signup form in the config or is just trying to manually extend SignupForm.  I am unable to confirm this but it *looks* to be valid.

This seems like this is a design issue, namely, SignupForm extends [a dummy signup form](https://github.com/pennersr/django-allauth/blob/37704c3298b8d1e7ba40f78b680197d60788ce55/allauth/account/forms.py#L211) when there is no specified custom form. I suspect the user is trying to extend SignupForm directly w/o configuring a custom form.

I am curious the reason for this and if it is still necessary to do it this way.  I think it would be more intuitive to have users inherit SignupForm instead of SignupForm inheriting the custom form.  **Doesn't this mean any methods in SignupForm cannot be overriden by our custom forms?**

**Comment by pennersr** [comment]
There reason is explained here: https://github.com/pennersr/django-allauth/issues/267#issuecomment-17966042

For most use cases, you should not derive from `SignupForm`, instead, you should create your own form and point to it using `ACCOUNT_SIGNUP_FORM_CLASS`.

Like so:

```
class PerformerSignupForm(forms.Form):
    is_performer = forms.BooleanField(
	required=False,
	widget=forms.HiddenInput(),
	initial=True,
    )
```

This is intentional. Not all of these fields may end up on a user model. And, you could also do something like this:

```
is_performer = Performer._meta.get_field("is_performer").formfield()
```

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2237
