### ISSUE TITLE
[apple] Any plans to include Apple's new "Sign In with Apple"?

### ISSUE THREAD

**Issue by eillarra** [pennersr/django-allauth#2315]
It seems it has been designed using OAuth and open standards... so we might be able to include it.

> The Sign In with Apple REST API is a web service that connects you to Apple's authentication servers. Use this service to onboard new users quickly and securely, allow them to log into your website with their Apple ID, and verify a user session with two-factor authentication.

References:
- <https://developer.apple.com/documentation/signinwithapplerestapi>

**Comment by zmh** [comment]
Would love this as well!

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by frankvanrest** [comment]
Although I respect your time and the work you (have) put into allauth @pennersr, https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue does not apply here. I think "Sign In with Apple" will be very relevant in a couple of months when the new iOS and macOS are launched. Can I help with making this a reality?

**Comment by pennersr** [comment]
You're right, the link does not apply. Still, this issue is a feature request for adding a new provider. Simply filing a feature request is not going to help in moving things forward, and there are already too many open tickets as it is. So yes, definitely interested in adding support for this, but please file a pull request instead.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2315
