### ISSUE TITLE
Unconfigured providers should be ignored instead of throwing an ImproperlyConfigured exception

### ISSUE THREAD

**Issue by olivierdalang** [pennersr/django-allauth#2343]
Hi !

Currently, an exception is thrown when a provider is added to INSTALLED_APPS but not configured from the admin : `django.core.exceptions.ImproperlyConfigured: No Facebook app configured`

IMO, it would be much better to just ignore unconfigured providers from the providers registry. This would allow apps to work out of the box. This would also allow adding several providers extensions, and leaving it to the website manager to enable the providers he actually wants from django admin. We could still have a warning in the logs to help out beginners.

In my setup, this issue means that when I deploy my app from scratch, I get an error out of the box (as the homepage redirects guests users to the login screen). It also prevents using the social login screen for the admin if you want to configure the app from the admin.

Thanks

**Comment by adamhooper** [comment]
This is a concern when configuring dev environments, too. And test environments.

I expect my project to have 100 collaborators, and I only expect 5 of those people to need to fiddle with SocialApps. I also expect tests to run without social accounts configured. How does one accomplish these tasks?

I tried a janky monkey-patch to back SocialApps with flat-file config. (The idea being, different devs would set up files as they need them, and we'd have a file on production.) That failed because OAuth/OAuth2 `SocialToken.app` is a foreign key.

I feel this is an urgent bug. The way I see it, every developer who uses a Django app with socialaccounts sees a 500 error by default. And it's my understanding that tests are similarly difficult to author. Yet here we are, buried at #2343 with a single participant. That means 2342 other bugs came first. I don't mean to complain -- rather, I want to help! But ... am I missing something obvious here? Are all the figurative cool kids high-fiving with some awesome solution, leaving me (and olivierdalang) in the dark?

Tomorrow I'll try an approach more similar to #2343.

**Comment by adamhooper** [comment]
A-ha. This only happens for Facebook. I guess the cool kids aren't using Facebook :).

**Comment by denisemauldin** [comment]
We're currently using an older version of django-allauth partially because of this functionality.  Is there a way to escalate this fix?  Can I help somehow?  Thanks!

**Comment by pennersr** [comment]
Fixed via affcfa09

**Comment by denisemauldin** [comment]
Thank you!

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2343
