### ISSUE TITLE
Connecting one social account to several local accounts

### ISSUE THREAD

**Issue by sandroden** [pennersr/django-allauth#2384]
I need to use an OAuth2 server to authorize several possible existing accounts (all belonging to the same person). The OAuth2 server sends a dictionary with all possible enabled accounts and I can switch from one to the other. Currently allauth stores "the" local account as `socialaccount.user` and in the login phase I was not able to circumvent this. I only get logged in as that user. 
Is there a way to force a specific user amongst the enabled users? I tried in `populate_user` but that gets overwritten and `lookup` in the end forces the match found in SocialAccount.

**Comment by pennersr** [comment]
So, by authenticated at your oauth server you get immediate access to multiple users? So I would expect that the oauth server hands over a list of user IDs of all those users. You would need a custom provider I guess that let's the user choose from one of those. Closing, this issue is not really actionable.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2384
