### ISSUE TITLE
Google Provider Error

### ISSUE THREAD

**Issue by steverecio** [pennersr/django-allauth#2443]
When I try social authentication with Google the provider returns a KeyError (see stacktrace below). I read [here](https://medium.com/@gonzafirewall/google-oauth2-and-django-rest-auth-92b0d8f70575) to modify the extract_uid method. How can I provide my adapter a modified GoogleProvider class? Or maybe the packaged provider should be fixed?

```
django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_auth/views.py", line 104, in post
django_1        |     self.serializer.is_valid(raise_exception=True)
django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 236, in is_valid
django_1        |     self._validated_data = self.run_validation(self.initial_data)
django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_framework/serializers.py", line 437, in run_validation
django_1        |     value = self.validate(value)
django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_auth/registration/serializers.py", line 122, in validate
django_1        |     login = self.get_social_login(adapter, app, social_token, access_token)
django_1        |   File "/usr/local/lib/python3.6/site-packages/rest_auth/registration/serializers.py", line 57, in get_social_login
django_1        |     social_login = adapter.complete_login(request, app, token, response=response)
django_1        |   File "/app/project/users/adapters.py", line 47, in complete_login
django_1        |     login = self.get_provider().sociallogin_from_response(request, extra_data)
django_1        |   File "/usr/local/lib/python3.6/site-packages/allauth/socialaccount/providers/base.py", line 86, in sociallogin_from_response
django_1        |     uid = self.extract_uid(response)
django_1        |   File "/usr/local/lib/python3.6/site-packages/allauth/socialaccount/providers/google/provider.py", line 43, in extract_uid
django_1        |     return str(data['id'])
django_1        | KeyError: 'id'
```

**Comment by steverecio** [comment]
Fix provided in #2444

**Comment by matthijskooijman** [comment]
I just set up the Google provider here as well, which works as expected.

Tracing the allauth code, I see that the failing dict comes from `extra_data` here: https://github.com/pennersr/django-allauth/blob/5b9b85593e683da28897635e9179b41f7db95ee1/allauth/socialaccount/providers/google/views.py#L16-L26

IOW, it comes from the response to the `userinfo` endpoint. Even though I could not find any proper docs on that, all examples I found talk about `id`, and `sub` is apparently a property of some other oauth response (not sure which). Dumping the data in my install shows the `id` property is present, but `sub` is *not* (i.e. your PR would break things for me).

Looking at your backtrace, it seems that the failing data originates here:

```
django_1        |   File "/app/project/users/adapters.py", line 47, in complete_login
django_1        |     login = self.get_provider().sociallogin_from_response(request, extra_data)
```

That is not Allauth code, but presumbly some other project-specific code. Looking at [the url you posted](https://medium.com/@gonzafirewall/google-oauth2-and-django-rest-auth-92b0d8f70575) that shows indeed an alternative implementation that does not call the userinfo endpoint, but does something else.

Instead of changing `extract_uid`, as suggested on that page and in your PR, I would suggest changing that adapter class to be compatible. e.g. adding this line just after where `extradata` is assigned:

    extradata['id'] = extradata['sub']

That should make things work for you without having to modify allauth. Alternatively, I think you could also subclass the `GoogleProvider` class to modify its `extract_uid` method (which is probably cleaner).

I would suggest closing this issue, as it is not an issue in allauth itself, but with a custom adapter.

**Comment by steverecio** [comment]
@matthijskooijman I did in fact get this working by using a custom adapter ([see comment here](https://github.com/pennersr/django-allauth/issues/418#issuecomment-576937532))

**Comment by pennersr** [comment]
https://django-allauth.readthedocs.io/en/latest/faq.html#why-did-you-just-close-my-issue

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2443
