### ISSUE TITLE
DigitalOcean connector always redirects to Aauthorization

### ISSUE THREAD

**Issue by datageek** [pennersr/django-allauth#2506]
Currently when attempting to build a login with DigitalOcean, each time a user attempts to login after their signup they are sent to the DigitalOcean Authorization page again. Ultimately, since they already have an account, I would like the users just to be taken into their dashboard. Is this a function of allauth or a function of how DigitalOcean does it's authentication?

**Comment by 9mido** [comment]
Do you mean allow users to login with their digitalocean username and password to access your site or do you mean every time your users on your site sign up with allauth for the first time on your site they are redirected to digitalocean since your site is hosted on digitalocean?

**Comment by iarp** [comment]
DigitalOcean's oauth api has several prompt types to choose from. Unfortunately none of them do what you want. You can see a list of available prompt choices here: https://developers.digitalocean.com/documentation/oauth/#prompts

- select_account is the default and forces the user to select the account.
- login forces the user to login to DigitalOcean every time
- none (literally the word none) redirects the user back to your site with the error for you to display such as not logged in, had no given consent yet, and lastly if they are already logged into DO then it works as you want.

You can try out the prompt types on your own system via the follow setting

```python
SOCIALACCOUNT_PROVIDERS = {
    'digitalocean': {
        'AUTH_PARAMS': {
            'prompt': 'none'
        }
    },
}
```

**Comment by iarp** [comment]
I managed to get this working using a custom provider.

- Copy the built-in digitalocean folder `allauth/socialaccount/providers/digitalocean/` into your own project
- Remove ``allauth.socialaccount.providers.digitalocean`` from ``INSTALLED_APPS`` and use the path to your own digitalocean folder that you copied.
- Add the `'prompt': 'none'` setting as seen in above comment.
- It's not a fully tested thing but it's worked in my own personal testing

All changes listed below are all within `views.py` only.

Add the following to the top

```python
from django.http import HttpResponseRedirect

from allauth.socialaccount.providers.digitalocean.provider import DigitalOceanProvider
from allauth.socialaccount.providers.base import AuthAction
from allauth.socialaccount.helpers import render_authentication_error
from allauth.socialaccount.models import SocialLogin
from allauth.socialaccount.providers.oauth2.client import OAuth2Error
```

Add the following above the `oauth2_login = ` lines

```python
class ResendCallbackView(OAuth2CallbackView):
    def dispatch(self, request, *args, **kwargs):
        if request.GET.get('error') in ['login_required', 'consent_required']:

            prompt = 'login'
            if request.GET.get('error') == 'consent_required':
                prompt = 'select_account'

            provider = self.adapter.get_provider()
            app = provider.get_app(self.request)
            client = self.get_client(request, app)
            action = request.GET.get('action', AuthAction.AUTHENTICATE)
            auth_url = self.adapter.authorize_url
            auth_params = provider.get_auth_params(request, action)
            auth_params['prompt'] = prompt
            client.state = SocialLogin.stash_state(request)
            try:
                return HttpResponseRedirect(client.get_redirect_url(
                    auth_url, auth_params))
            except OAuth2Error as e:
                return render_authentication_error(
                    request,
                    provider.id,
                    exception=e)

        return super().dispatch(request=request, *args, **kwargs)
```

Replace the following line

```python
oauth2_callback = OAuth2CallbackView.adapter_view(DigitalOceanOAuth2Adapter)
```
with the following line

```python
oauth2_callback = ResendCallbackView.adapter_view(DigitalOceanOAuth2Adapter)
```

Essentially what happens is:

- Allauth sends the user to DO with prompt=none
- DO redirects them back to your site no matter what happens. 
- If they return without an error message, login occurs like normal.
- If they return with an error code of `login_required` or `consent_required`
  - allauth then redirects them back to DO with a new prompt setting where:
    - `login_required` changes `prompt` to `login`
    - `consent_required` changes `prompt` to `select_account`
- Otherwise it'll show the social network failure message

Of course from here on out its on you to make sure the custom system works anytime allauth updates.

**Comment by derek-adair** [comment]
@pennersr Not quite sure here but it seems invalid.  If i am logging in with social auth it seems that I *should* be taken to the account_select auth on digital ocean, right?

**Comment by pennersr** [comment]
But you can already choose that -- see https://github.com/pennersr/django-allauth/issues/2506#issuecomment-673751925

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2506
