### ISSUE TITLE
Prevent inactive users from logging in

### ISSUE THREAD

**Issue by bodgerbarnett** [pennersr/django-allauth#2519]
I am using the is_active flag on a user to allow users to deactivate their accounts on my site.

But if they then try and log in to their account, they get redirect to an "Account Inactive" page, which is not what I want. I'd prefer it if it looked like they just didn't have an account in this instance. Essentially, I'm trying to allow users to delete their account but just using the is_active flag to denote "deleted" accounts, so I can preserve the links to their names etc. in the database.

Am I going about this the wrong way? Or have I missed something here?

**Comment by pennersr** [comment]
You cannot use is_active to delete an account. That is by design, if you go that way the user could signup again and you would have two equal email addresses in your database, on for your semi-deleted user, and one for the new signup. Also, what you are after is legally dubious. In Europe at least, if users want to have their account deleted all personally identifiable information needs to be wiped, so keeping their name in the database is wrong. All in all, is_active is not meant for all of this.

**Comment by bodgerbarnett** [comment]
But in the offiicial Django docs (https://docs.djangoproject.com/en/3.0/ref/contrib/auth/#django.contrib.auth.models.User.is_active), it says:-

> We recommend that you set this flag to False instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break.

**Comment by pennersr** [comment]
What is said there is just one part of the puzzle. The missing part is pseudonymizing data you have of this user. Meaning, throwing a way personal identifiable information, such as name and email, and likely all the (project) specific data the user created within your site.  Once you do that, the user will not be able to login anymore, so he won't be able to see the "Account inactive" page. But, actually doing this goes beyond the scope of allauth as it involves throwing away and/or pseudonymiing project specific data. As stated, this is not something optional, in Europe for one this is legally required according to the GDPR.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2519
