### ISSUE TITLE
Cleanup expired email confirmation

### ISSUE THREAD

**Issue by mbaechtold** [pennersr/django-allauth#252]
Is there a way to clean up expired email confirmations?

Say we have two users Alice (alice@example.com) and Bob (bob@example.com). Now Alice creates an account and uses alice@example.com for her primary addresses. But she also adds bob@example.com as an additional email without confirming it (because she does not have Bob's password for the mail account).

Now Bob wants to signup using bob@example.com which is not possible.

What about a management command which will delete non-verified emails older than `timezone.now() - timedelta(days=app_settings.EMAIL_CONFIRMATION_EXPIRE_DAYS)`?

**Comment by MaxKoroteev** [comment]
https://github.com/pennersr/django-allauth/blob/master/allauth/account/managers.py#L48

This code handles the deletion of EmailConfirmation not non-verified EmailAddress

or i am mistaking?

**Comment by HEdingfield** [comment]
I noticed that, if you create an account and then try to login without verifying (so it generates a few more email confirmations), all email confirmations still exist once users complete the verification of their address.

It seems to me like allauth should either a) clean up all confirmations associated with that email address once verification is complete, or b) clean up all unused confirmations if there's a valid reason to keep the actual one they used to verify their address around.

I personally can't think of why these should persist in the database at all after they've been used, but maybe I'm missing something.

**Comment by banagale** [comment]
Here's a request for this to be re-opened, since the HMAC solution [does not allow for using cooldown](https://github.com/pennersr/django-allauth/issues/1921) to conditionally allow additional confirmation emails to be sent.

If you're building the typical email change flow seen on most consumer apps, you want to be able to know if you should allow the user to have enabled UI to send another email. This means the original implementation is still valuable. It simply needs to do a bit of cleanup.

One way to handle this would be to add code to the `confirm_email()` method of the default account adapter that if HMAC is false, look for and remove any EmailConfirmations connected with the validated address on that user's account.

**Comment by 9mido** [comment]
Now we have ACCOUNT_MAX_EMAIL_ADDRESSES = 1 to prevent a user from adding another email address that is not their own. 

It looks like EmailConfirmationManager has delete_expired_confirmations which the links above are referring to. The hashtag line in the old links is wrong. 

Here is a custom management command example:

```
#Command: python3 manage.py file

from django.core.management.base import BaseCommand

import datetime
from django.utils import timezone
import pytz

from allauth.account.models import EmailAddress
from django.contrib.auth.models import User

class Command(BaseCommand):
    help = 'Delete users who have unverified email addresses that are between 1-2 days old'

    def handle(self, *args, **kwargs):
        recent_joined_users = User.objects.filter(date_joined__gt=timezone.now() - timezone.timedelta(days=2), date_joined__lt=timezone.now() - timezone.timedelta(days=1))
        for x in recent_joined_users:
            emails = EmailAddress.objects.filter(user=x, verified=False).values_list('user', flat=True)
            for y in emails:
                User.objects.get(id = y).delete()
```

**Comment by quroom** [comment]
@9mido Thanks a lot!
I made it based on your code!

**Comment by 9mido** [comment]
@quroom You're welcome. Curious what you made and how it differs? Maybe you could share your solution as well? 

@amin1998sh Looks like in account views.py class ConfirmEmailView you should see EmailConfirmation.DoesNotExist and it will 404 by default if expired. So you don't want it to be a 404 returned and something else instead? 

You can redirect URLs in general like this:

https://stackoverflow.com/questions/14959217/django-url-redirect

https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django

If you want to customize the 404 page try this:

https://stackoverflow.com/questions/17662928/django-creating-a-custom-500-404-error-page

But otherwise, a PR could be made where you make a setting like ACCOUNT_EMAIL_EXPIRATION_REDIRECT_URL inside of app_settings.py so anybody could enter a custom expiration URL. Then you could use return HttpResponseRedirect(app_settings.EMAIL_EXPIRATION_REDIRECT_URL) to do it. (Follow my delete account PR and you could see what I did for that).

**Comment by quroom** [comment]
```recent_unverified_joined_users = CustomUser.objects.filter(date_joined__lt=timezone.now() - timezone.timedelta(self.ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS), emailaddress__verified=False)
        if recent_unverified_joined_users.count():
            deleted_count = recent_unverified_joined_users.delete()
            print('cleanupregistration completed. Deleted user count=%d' % deleted_count)
        else:
            print('cleanupregistration completed. There is no user has to be deleted.')
```

Not thing really different with yours.
I just want to show logs. And this code will be run by cron.

**Comment by amin1998sh** [comment]
@9mido The thing is, when the user clicks on a wrong activision link, recieves 200 OK, but according to what you said and according to raise Http404() in account/views.py line 385 it should send 404 status code.

**Comment by quroom** [comment]
@amin1998sh HTTP404 exception is catched here again.
https://github.com/pennersr/django-allauth/blob/353386216b79f16709e97bb487c0bbbba2bc0c71/allauth/account/views.py#L297
And then return response. That's why response status is 200.

**Comment by 9mido** [comment]
@quroom Good catch thank you for pointing it out since I missed that. I am wondering now if it is supposed to give 200 OK on purpose because when /accounts/confirm_email/ is not yet expired, it should give a 200 OK redirect and allow people to confirm their emails. Correct me if I am wrong, but since an expired email redirects to the same /accounts/confirm_email/, it is currently doing 200 OK but forcing itself to 404 without the 404 status code. 

This should definitely be fixed because it does not make sense to 200 OK when the email is expired it should actually give a status of 404. Besides the command line, we could check in chrome inspect network tools to see if a 404 status is truly received.

**Comment by 9mido** [comment]
Personally, I don't think anything needs to be changed here. I like that when clicking an expired email link, you are redirected to a page with 200 status that says "Confirm E-mail Address - This e-mail confirmation link expired or is invalid. Please issue a new e-mail confirmation request." You could always customize the template / message to say whatever you want in the expired link scenario.

**Comment by mbaechtold** [comment]
Closing this issue due to its age.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/252
