### ISSUE TITLE
Security Flaw

### ISSUE THREAD

**Issue by AnkitMitraOfficial** [pennersr/django-allauth#2716]
In the django-admin site a attacker may try to use brute force attack to get in,there should be some kind of settings which blocks the attacker to stop for trying multiple passwords for few minutes,maybe after 3-5 tries

**Comment by 9mido** [comment]
You can revamp your admin login's security by:

Adding recaptcha to django-admin
Using django-otp for 2FA
Using django-admin-honeypot
Changing the url of admin to something else

Since your specific use case is brute force, check out django-axes or django-defender.

But implementing into allauth wouldn't be a bad idea either I suppose.

**Comment by AnkitMItraOfficial** [comment]
Okay👍👍🔥🔥😁

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2716
