### ISSUE TITLE
Does Django-allauth have a built in way of deleting accounts?

### ISSUE THREAD

**Issue by nh916** [pennersr/django-allauth#2726]
As I have been using django-allauth in more projects I have noticed over and over that deleting accounts is missing and I thought it would complete the solution. I have used Django allauth for years and love it and would love to see it included

**Comment by 9mido** [comment]
https://github.com/pennersr/django-allauth/issues/344

**Comment by nh916** [comment]
Oh yeah I saw that one but I thought it would be way better if it was built in. Allauth does a great job with every part of the accounts process so I thought this is the last thing that could really complete their whole framework from registration to deletion

**Comment by 9mido** [comment]
I agree to some extent since GDPR basically has "the right to erasure" built into it. 

Although I see pennersr's point about different implementations of deletion depending on the type of website. If this were something like Facebook picture uploads I would also want to delete the pictures along with the account with models.CASCADE and not have the people who shared the pictures access them anymore also and have them 404 or hidden or something. Maybe the comments and URL exist but the picture / comments will not. Like if this were a child's provocative pictures those need to be deleted also along with everything else the child posted.  

But for other websites without media files associated with the account or even just saved profile text based information for that user, it should be part of allauth since deleting everything is now part of many apps nowadays compared to 7 years ago when the issue was first created.

**Comment by pennersr** [comment]
See: https://github.com/pennersr/django-allauth/pull/2786#issuecomment-977960052

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2726
