### ISSUE TITLE
ForeignKey in custom User model form.save(commit=False) needed

### ISSUE THREAD

**Issue by finevine** [pennersr/django-allauth#2747]
I have a FK in my custom User model. To create an instance of this FK model, when creating a user, I need to have
`class AccountSignupView(SignupView):

    def __init__(self,*args,**kwargs):
        super(SignupView, self).__init__(*args,**kwargs)

    def form_valid(self, form, *args, **kwargs):
        token_value = kwargs.get('token', '')
        self.user = form.save(self.request, commit=False)
        # Then do my logic
 `
 But signupForm has no commit in kwargs. What should I do?

**Comment by yedpodtrzitko** [comment]
- either inherit `SignupForm` and override its `save()` method; internally it calls `adapter.save_user()` which has the `commit` parameter, so you can do the custom logic there instead of in `form_valid()`

- or override [settings.ACCOUNT_ADAPTER](https://django-allauth.readthedocs.io/en/latest/configuration.html) with a class inherited from the default adapter, override its `save_user()` (which again does the user model saving) and call the parent method with `commit=False`....

**Comment by derek-adair** [comment]
Close as won't fix / support request.

@yedpodtrzitko nailed it, thank you for your help.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2747
