### ISSUE TITLE
Email verification issues

### ISSUE THREAD

**Issue by joshuakoh1** [pennersr/django-allauth#2757]
If the max emails per user setting is set to 1, there's absolutely no reason for the user to have access to the email address management page at /accounts/email/. There needs to be a specific view with the sole function of generating the verification email for the user's default email that can be accessed directly. Additionally, with a single user email, there is no basis for accepting email as a POST value.

There also seems to be an issue where the user can still request for verification emails even after the address has been verified. This can easily overwhelm email quotas if abused.

**Comment by 9mido** [comment]
@joshuakoh1 

I agree with the denying users from accessing /accounts/email/ if ACCOUNT_MAX_EMAIL_ADDRESSES = 1

For now the only workaround in urls.py is:

```
from django.views.defaults import page_not_found
url('^accounts/email/', page_not_found, {'exception': Exception()}),
```

But it should probably be built into allauth without needing to do that. 

Please see PR feat(timeouts): add timeout system to prevent spamable actions 263

That PR will solve the spam/abuse issue if merged. Glad to see I am not the only one who thinks that. I don't know what the hold up is and why a decision is taking so long to merge it since it solves multiple issues.

I made some more issues / comments regarding abuse. Please see for further details:

Spam Clicking Email Re-send Verification Button 2595

Password Reset Emails Not Subject to Cooldown 2167

**Comment by joshuakoh1** [comment]
@9mido routing accounts/email to page_not_found also disables the ability to generate verification email. Right now, I'm using a button that posts action_send to accounts/email to generate the email https://github.com/pennersr/django-allauth/blob/52978e2e5c7e1755f8b904aea65b3cf305d2c92c/allauth/account/views.py#L442. Will probably have to copy the entire view into a separate view which is a lot of extra work for something that should already be built in.

As for the email being sent as a POST value, the email address to be verified should not even be a POST value for single emails (https://github.com/pennersr/django-allauth/blob/52978e2e5c7e1755f8b904aea65b3cf305d2c92c/allauth/account/views.py#L446). An easy fix would be to set email = request.user.email (https://github.com/pennersr/django-allauth/blob/52978e2e5c7e1755f8b904aea65b3cf305d2c92c/allauth/account/views.py#L464) if there is no POST value.

**Comment by 9mido** [comment]
@joshuakoh1 

What are your allauth settings? Can you provide more code? Allauth version, django version, etc? I have:

ACCOUNT_MAX_EMAIL_ADDRESSES = 1
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

And I use the urls.py code above to block users from accessing /accounts/email to be able to re-send email verification to avoid abuse until the PR is merged. But I have no problem getting the email verification sent to new signed up users. Why would you need to have action_send sent there?

**Comment by derek-adair** [comment]
@pennersr fairly complex issue here.  *note*: every linked PR/issue is closed that @9mido mentions.

1. I *believe* throttling has been implemented since this issue went stale.
2. probably trivial to only send emails if the email isn't verified??
3. dispassionate about invalidating POST'd emails in this case
4. A ACCOUNT_MAX_EMAIL_ADDRESS setting is not worth adding to the already complex setting model.

I'd close this one @pennersr as it *seems* like these issue's have been addressed.  Besides, the specific and complex suggestions are well within allauth's ability to extend and support w/o modifying allauth.

**Comment by pennersr** [comment]
I don't think this is a valid ticket. Max emails of 1 is a weird use case, it indirectly prevents users from changing their email address. Now, there can of course be cases where you want to prevent users from changing their email, but that should be done differently, not via a max of 1.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2757
