### ISSUE TITLE
Feature Request: Prefill option for E-Mail on signup form

### ISSUE THREAD

**Issue by sowinski** [pennersr/django-allauth#2861]
Hi,

would be nice if I could send a link to a customer with a prefilled version of the registration form.

For example:
https://www.exmaple.com/accounts/signup/?email=cumter@email.de

**Comment by gmso** [comment]
Implemented on PR #3003

**Comment by chrislan815** [comment]
i got the same thought, too. This would be amazing!

**Comment by sagejason** [comment]
@pennersr This was a great add for the sign up forms. Any reason it couldn't be extended to Login Forms, Password Reset, etc? 

If you don't have objections, I can write it and send a pull request when I've got time.

**Comment by pennersr** [comment]
See: 

- https://github.com/pennersr/django-allauth/pull/3003#issuecomment-1699824363

- https://github.com/pennersr/django-allauth/pull/3003#issuecomment-1699681522

**Comment by sagejason** [comment]
Thank you for the link, we'll go ahead and handle this browser side, as per your comments. 

Since I saw other comments wonder about use case, here is one just for context: we have old users in our system that we are trying to reactivate via digital ads. They are returning to our site and browsing around before attempting to signup. Many are having to type their email in three different forms to reactivate, leading to drop off. 

- They try to sign up and get an error because their email is already in use. 
- Then they get to the login page and attempt to enter their email and password and make multiple attempts.
- Then they get to the password reset page and enter their email again. 

After that, they go through the password reset flow before logging in. 

So from the user experience of someone we are trying to reactivate, it seems a frustrating experience to have to type in their email three different times and then going through a password reset flow.

The hope was that after a signup attempt with an existing email, we could redirect to a prefilled login form to eliminate at least one of those entries. Because prefill on SignUp forms was delivered, we thought it would be cleaner to handle all forms the same way. 

It's not a big job to handle other forms with JavaScript, so this isn't a big issue.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2861
