### ISSUE TITLE
Require verified email address before requiring activation.

### ISSUE THREAD

**Issue by derek-adair** [pennersr/django-allauth#2904]
Currently in the [perform_login](https://github.com/pennersr/django-allauth/blob/master/allauth/account/utils.py#L143) it checks to see if a user is active before checking to see if email confirmation is required.  It makes sense, from the admin perspective, that this is reversed.

**Comment by 9mido** [comment]
@derek-adair Just to be even clearer, you mentioned in the first post that you want the checks done for perform_login function. But that function refers to the logging in of the users. This function does not actually write to the database saying that the user is active or their email is verified. Do you actually want to change the order of the username activation/email verification creation via the database and write to the database in that new order all in 1 shot after signing up? In other words, when the user signs up, we are writing to the database and changing the ordering to be: EmailAddress model verified = true then User model is_active = true. 

One problem with changing the ordering is it disrupts the process of telling the user that they need to verify emails. Right now we want users to login even if they are unverified so that they could see this page:
https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/verified_email_required.html

If changing the order but not doing the user activation and email verification all in one shot in the database after signups, we need to tell the user on the login page/form to verify their email as a validation error or `messages.error(request, 'Please verify your email.')`. This way, the user can see that they need to verify their email address first before becoming active and being able to login. Once they verify their email address, then the User model needs to change from is_active = false to is_active = true.

So after a user signs up, their login/authentication needs to be disabled until they verify their email address. 

To check if an email is verified: 
```
from allauth.account.models import EmailAddress
email = request.user.email
if EmailAddress.objects.filter(email=email, verified=True).exists() is True:
```

To check if a user is active:
```
#from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
User = get_user_model()
if User.objects.get(username=request.user).is_active is True:
```

Some other places to look:
perform_login
complete_signup
setup_user_email

As for the function where the user gets saved into the database it seems like it happens in class SignupView and ConfirmEmailView. Another thing to consider is the user might have a custom user model.

In allauth account views.py you can see:
```
        # Don't -- allauth doesn't touch is_active so that sys admin can
        # use it to block users et al
        #
        # user = confirmation.email_address.user
        # user.is_active = True
        # user.save()
```

If you want to make a PR @derek-adair I am interested in seeing how you do it or please share your code in this thread. But hopefully this should get you started.

**Comment by derek-adair** [comment]
@9mido 
>Just to be even clearer, you mentioned in the first post that you want the checks done for perform_login
I have **no** preference in where/how it is done as long as **the email required view appears before the inactive user view**.  My desired flow here *seems to be* easily achievable by swapping the User.is_active check below the confirm email logic in the perform_login function

>In other words, when the user signs up, we are writing to the database and changing the ordering to be: EmailAddress model verified = true then User model is_active = true at the same time. 

No this does not have to do with signup.  This is purely the login flow.  Let me try to be more explicit.

```
1) User signs up (User.is_active = False, EmailAddress.verified = False).
2) User logs in and is told to verify email
3) User verifies email
4) User logs in and is told they are waiting for admin approval
```

**Comment by derek-adair** [comment]
My main complaint is from an admin perspective;

If I require a verified email, why would I want to activate them before they are verified?

**Comment by pennersr** [comment]
This issue is about the semantics of "is_active". Unfortunately, there is no clear definition of what true or false represents here. 

https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_active

What is clear though is this:

> We recommend that you set this flag to False instead of deleting accounts

Meaning, `False` really suggests that a user account should not exist. That conflicts with the way you are using it, as you are using `is_active` for manual verification purposes. A user who is actively using the system but has not verified yet is a user that exists and is active, hence, allauth expects those users to have `is_active=True`. 

Given the above, I recommend you introduce a new "is_verified" field for your use case. Then, you can also have the situation "is_verified and not is_active" for users that were once verified but are no longer using the system.

All in all, the current allauth implementation is fine here.

**Comment by derek-adair** [comment]
well said; I am entirely convinced.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/2904
