### ISSUE TITLE
Account Inactive Page Not Working 

### ISSUE THREAD

**Issue by OfficialRuby** [pennersr/django-allauth#3077]
I'm using django-allauth 0.49.0 package, I have set a registered USER `is_active` to `False` but each time I tried to login as this user, I'd get the error `The username and/or password you specified are not correct.`. Django version is 4.0.3

**Comment by pennersr** [comment]
As per Django semantics, `is_active` implies the account is deleted, hence, the behavior is to be expected:

https://docs.djangoproject.com/en/4.0/ref/contrib/auth/

"Boolean. Designates whether this user account should be considered active. We recommend that you set this flag to False instead of deleting accounts; that way, if your applications have any foreign keys to users, the foreign keys won’t break."

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3077
