### ISSUE TITLE
Login into multisite

### ISSUE THREAD

**Issue by bvj** [pennersr/django-allauth#3145]
I am looking for a way to share information about logged-in user between individual sites at Wagtail multisite. By that I mean the possibility to log in on one site and by that be logged in on all the others.
All sites use the same base domain.

**Comment by BoPeng** [comment]
I have a similar problem in that the user belongs to one of the sites and I would like to authenticate the users from the main site and redirect them to the right sub-site. My current approach is to modify the page `LOGIN_REDIRECT_URL` so that its `get()` request will redirect users to the right `sub_domain/LOGIN_REDIRECT_URL`. This **does not work now** since the users are asked to login again.

I think the root problem is that authentication (the session cookie) is related to the site where the user is authenticated. If this is true, I may need to use `sub_domain/login.html` to login (something like `post` to the login form of another site), and you may have to go deeper (e.g. modifying the authentication middleware).

**Comment by pennersr** [comment]
Closing -- this goes beyond the scope of allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3145
