### ISSUE TITLE
How to custom redirect for complete_social_login / _process_signup?

### ISSUE THREAD

**Issue by jackkinsella** [pennersr/django-allauth#3151]
I'm using Django allauth as the backend for logins with some Android/iOS native apps and therefore need to output deep links (i.e. ones with custom protocols like `myapp://complete_login/{some-identifier}`). Doing so requires a lot of control over redirects. 

This is mostly fine thanks to the five redirects already present in the library (https://django-allauth.readthedocs.io/en/latest/advanced.html#custom-redirects) -- a big thanks to whoever added these :) 

One situation I couldn't figure out yet was when someone signs up for the first time and they need to go to a URL to gather more information (e.g. to choose a username). I wasn't able to find a place in the public API to insert the redirection code I needed. Any ideas?

**Comment by iarp** [comment]
It's hardcoded to go to the socialaccount_signup view https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/helpers.py#L23

**Comment by pennersr** [comment]
If you need to ask additional information like username for social signups, then you should turn auto signup off, and add the additional info you would like to be filled out to the custom signup form. So I think this is covered. Otherwise, please provider more info on your exact flow.... it's now not fully clear where you would like to intervene.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3151
