### ISSUE TITLE
Google Provider doesn't provide picture anymore

### ISSUE THREAD

**Issue by Braintelligence** [pennersr/django-allauth#3240]
Hello everyone.

I'm not sure if it's an issue with allauth or with Google but since I've updated allauth to the current version I don't receive the key `picture` anymore in the extra_data.

Thus `get_avatar_url` also fails.

I still have the picture url in social accounts that didn't relog yet.

Any idea what might be going wrong?

**Comment by Braintelligence** [comment]
So when I saw this: https://github.com/iMerica/dj-rest-auth/issues/465#issuecomment-1398233045

I compared commits for the mentioned views.py.

v0.51.0: https://github.com/pennersr/django-allauth/blob/0.51.0/allauth/socialaccount/providers/google/views.py

v.0.52.0: https://github.com/pennersr/django-allauth/blob/0.52.0/allauth/socialaccount/providers/google/views.py

And there is really some significant difference there. I will try downgrading next and see if my issue will be fixed by that. It seems multiple persons had luck with that:

https://github.com/pennersr/django-allauth/issues/3228#issuecomment-1387225509
https://github.com/iMerica/dj-rest-auth/issues/465#issuecomment-1380243422

**Comment by Braintelligence** [comment]
As I suspected; reverting to v0.51.0 brought profile pictures back again.

I hope this is enough information to fix the issue; I'm not sure if just providing a PR that reverts above mentioned code will be accepted. There are many open PRs, so I'm not sure if it would get any attention...

**Comment by fdemmer** [comment]
This is the commit, that changed things: e6c5a0478fe06198eeb976fbb47515edc5a59828

Instead of fetching information from https://openidconnect.googleapis.com/v1/userinfo the "identity data" from the JWT is used directly. You can see an "example" of the data contained in the JWT in the [tests](https://github.com/pennersr/django-allauth/blob/master/allauth/socialaccount/providers/google/tests.py#L40)... it includes a "picture" field.

All this information should end up in the `SocialAccount.extra_data`.

For me this works with 0.53.1 and I can use `get_avatar_url()` on `SocialAccount` objects to get the picture URL.

Do you not get the expected data in `SocialAccount.extra_data`?

The [docs](
https://django-allauth.readthedocs.io/en/latest/providers.html#google) mention setting `AUTH_PARAMS['access_type']` to `offline` to receive a fresh token. Maybe that makes a difference (was not necessary for me)?

**Comment by pennersr** [comment]
Closing -- see https://github.com/pennersr/django-allauth/issues/3240#issuecomment-1481000286

**Comment by Braintelligence** [comment]
> Closing -- see [#3240 (comment)](https://github.com/pennersr/django-allauth/issues/3240#issuecomment-1481000286)

Can you please elaborate further on how that comment helps? See https://github.com/pennersr/django-allauth/issues/3240#issuecomment-1481156663

**Comment by pennersr** [comment]
That comment confirms that it works and explains how it is implemented. For me this issue is not further actionable, if you do find an issue in allauth please reopen, but there is not much point in keeping it open without a clear plan of action.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3240
