### ISSUE TITLE
Vulnerability: Password reset emails sent to unknown addresses

### ISSUE THREAD

**Issue by alexburner** [pennersr/django-allauth#3333]
Related issue: https://github.com/pennersr/django-allauth/issues/2360

My team just discovered this vulnerability — currently, a user can enter any email address in the password reset form, and that address will receive an email from our system. 

⚠️ This means a bad actor could "spam" a large number of addresses with these emails, and tank our domain reputation ⚠️

I understand that the `ResetPasswordForm` should submit successfully regardless, with `ACCOUNT_PREVENT_ENUMERATION=True`, to prevent users from determining who's registered with the system. 

But why send actually send an email to these unknown addresses? Couldn't `allauth` just fail silently, in that case?

I see the `_send_unknown_account_mail` method got added in the original `ACCOUNT_PREVENT_ENUMERATION` commit: https://github.com/pennersr/django-allauth/commit/7a719b64154840a8c6ff5c4301568f897721fcc0#diff-aca468f72aa7648b36b8ee86a25c3ade350120bc2769cd875e418b1f50574935R536

Could we get an additional configuration flag, such as `SEND_PASSWORD_RESET_TO_UNKNOWN_ADDRESSES=False`, to prevent this behavior?

**Comment by alexburner** [comment]
For posterity, we were able to override this with a custom form:

`mysite/forms.py`
```py
from allauth.account.forms import ResetPasswordForm

class CustomResetPasswordForm(ResetPasswordForm):
    def save(self, request, **kwargs):
        email = self.cleaned_data["email"]
        if self.users:
            self._send_password_reset_mail(request, email, self.users, **kwargs)
        return email
```

`settings.py`
```py
ACCOUNT_FORMS = {'reset_password': 'mysite.forms.CustomResetPasswordForm'}
```

---

It's worth noting that the `allauth` documentation recommends against skipping `super()` like this:
```py
# Ensure you call the parent class's save.
```
https://django-allauth.readthedocs.io/en/latest/forms.html#reset-password-allauth-account-forms-resetpasswordform

**Comment by pennersr** [comment]
The password reset is rate limited, mitigating the ability for a bad actor to spam like this.

The attack vector you are describing is not addressable by changing the password reset. The bad actor could just as well spam the signup page, that will result in sending email verification mails as well. But, that is rate limited as well.

So all in all, the issue is not fixable by focusing solely on the password reset. Built-in rate limiting already mitigates this. If that is not enough, you would need to resort to using a captcha system.

**Comment by benjaoming** [comment]
Nice with the rate limiting, but I doubt it's a guarantee against abuse in 2026.

> The bad actor could just as well spam the signup page, that will result in sending email verification mails as well.

Sign-up is disabled in many/most cases where this is a concern... which leaves the password reset as the only page that's openly sending emails to unknown addresses.

I think it sounds like this behavior should be configurable rather than letting people resort to monkey patching.

Is it okay to reopen or okay to open a new issue about this?

**Comment by benjaoming** [comment]
Oh LOL, we're on Codeberg now, apologies.

**Comment by benjaoming** [comment]
https://codeberg.org/allauth/django-allauth/issues/3333

**Comment by mainangaruiya** [comment]
i was also be  so alarmed on such if its still case in 2026

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3333
