### ISSUE TITLE
Two logins required for MFA

### ISSUE THREAD

**Issue by AlexDiede** [pennersr/django-allauth#3436]
With MFA activated I have to go through the login process twice to actually be logged in. To reproduce:

1. Follow the instructions to set up the [example project](https://github.com/pennersr/django-allauth/tree/main/example)
2. run 'pip install -U django-allauth[mfa]' so the dependencies are installed
3. log in as the super user you created in step one and activate MFA then logout
4. log in again using username/password, you will be brought to the authenticate screen, enter the code from your authentication app
5. you will be redirected back to the login page.  repeating step 4 will result in a successful login

**Comment by pennersr** [comment]
MFA is a special login stage. If you access any Django view that is not concerned with completing the stage, that means the user has moved away and the stage is wiped. Now, chances are you are seeing `/favicon.ico` in your runserver output, and 0.56 assumes the user moved away because of it. This is fixed here: 9f21675b

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3436
