### ISSUE TITLE
pre_social_login adapter cannot abort if Google social account's email matches user's email

### ISSUE THREAD

**Issue by Ponmo** [pennersr/django-allauth#3604]
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_EMAIL_VERIFICATION=False

When connecting to a Google social account via the accounts/social/connections page, I can usually abort the connection in pre_social_login. However, if the user chooses a gmail with the same email as their account, when pre_social_login is called, the social account is already connected and registered so that I cannot abort it.

If this is the expected behavior with SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True, then I will work around it. For context, I am attempting to limit the number of social accounts per user to one of each.

**Comment by pennersr** [comment]
I don't fully grasp the question. What do you mean by "abort the connection" ?

**Comment by Ponmo** [comment]
For example, I create an account with the email 123@gmail.com and sign in. Then I go to the accounts/social/connections to connect a Google Social Account. 


A. If I choose a Google Account with a different email (888@gmail.com), the pre_social_login happens before the add signal, meaning that if I raise an ImmediateHttpResponse in the pre_social_login, the social account won't be added and connected to the account. 
B. A. If I choose the Google Account with the same email (123@gmail.com), the social_account_added signal is emitted before the pre_social_login. That means even I raise the ImmediateHttpResponse in pre_social_login, the social_account is already connected to my account.

**Comment by pennersr** [comment]
What you describe above only happens when you have turned email authentication on (off by default). When you have it turned on, at step B account the social login with email 123@gmail.com is not treated as a new to be added account -- because of email authentication, the sociallogin having 123@gmail.com is treated as a login to the already existing account, and because you also have `SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT` an implicit add takes place during this step. So, this indeed to be expected.

You could override the `can_authenticate_by_email()` adapter method if you want to intervene earlier -- before the email authentication takes place.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3604
