### ISSUE TITLE
Email customization issues

### ISSUE THREAD

**Issue by EkoPages** [pennersr/django-allauth#3636]
I use rest-auth combined with allauth for registration
I customized the reigstration endpoints and also the email being returned to users

whenever I test it out in localhost it returns the email the way I want it to be returned

`Dear TestUser1,

Welcome to Ekopages, your gateway to sustainable education!

We're thrilled to have you join our community. To get started on your journey towards a greener future, please click the link below to confirm your email address:

https://ekopages.com/registration/account-confirm-email/NTE:1rUpCQ:qimz8K0QFUD5ZM8WbMlmcBqq3HSzNp0vNSziMaJRV44/

Once confirmed, you'll have full access to [ekopages.com](http://ekopages.com/), where learning meets sustainability.

Thank you for choosing Ekopages. Let's embark on this educational adventure together!

Green regards,
The EkoPages Team.
[ekopages.com](http://ekopages.com/)`

but whenever I push to production it returns

`Hello from !

Dear TestUser01,
Welcome to Ekopages, your gateway to sustainable education!

We're thrilled to have you join our community. To get started on your
journey towards a greener future, please click the link below to
confirm your email address:

https://ekopages.com/registration/account-confirm-email/ODI:1rYDAZ:9-iTNT6_wtKMwvWsrLLc1ATuzNwWIxAvTjUxLDP5G4Q/

Once confirmed, you'll have full access to [ekopages.com](http://ekopages.com/), where
learning meets sustainability.

Thank you for using !`

Ive modified the emails and even the custom adapter still no luck. What can I do to fix this issue?

**Comment by pennersr** [comment]
It's not fully clear what issue you are referring to. I suspect the issue is that one of those versions starts with "`Hello from !" and ends with "Thank you for using !`" ?

Those texts originate from this template:

https://github.com/pennersr/django-allauth/blob/main/allauth/templates/account/email/base_message.txt

If you are overriding that template, and you're seeing differences in localhost vs production, that really points to a deployment issue on your end and not an issue in django-allauth.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3636
