### ISSUE TITLE
Google accounts and '.' aliases

### ISSUE THREAD

**Issue by rthuffman** [pennersr/django-allauth#366]
Love your plugin, but I have uncovered a strange problem with Google accounts on OAuth2, just forwarding it to you as a possible future revision.

The idea is to strip periods from the username in the email address for the Google authentication package before saving them to the database.

See https://support.google.com/mail/answer/10313?hl=en - "Your address is similar but has more or fewer dots", etc.

Here's the workflow that surfaced this as a problem:
A user (let's say "somedude@gmail.com") signs up to a third-party service using their GMail account via OAuth2.  They then receive notifications from the service at the email address provided to them by Google.

The user then signs up at my site using Google via OAuth2, and I get a copy of their email address, only it's "some.dude@gmail.com" when he signs up with me.  I check the list of emails coming in to see if they're coming from a user who has signed into the site, and _if the user has changed their profile between the two signups_, the email addresses will be different.

I realize this is not a problem with your plugin, just pointing it out as a possible pitfall (that you may already be familiar with) with Google and relying on the ACCOUNT_UNIQUE_EMAIL=True setting.

Thank you for this package!

**Comment by lukeburden** [comment]
There's value to this proposal based on my experience managing a user-base in an app using all-auth. The main benefits being:

- reducing the chance of users accidentally creating multiple accounts when they themselves are inconsistent with the traditional login/signup flow
- allow for more precise, reliable account resolution (at login/signup using different social providers, if emails are considered verified) further reducing duplicate accounts / user confusion
- adding some level of friction to users intentionally trying to create multiple accounts, if you deem this as problematic in your use case

Would you be against an option to "normalize" gmail addresses in this way?

**Comment by pennersr** [comment]
I think you should be able to solve this by simply overriding the `clean_email`. Given that, and I don't think we need to support it in allauth directly. Also, whatever you do will not be fail safe, for example, you will not be able to recognize Google apps for domains email addresses, and, other providers are known to support the "+" as well...

**Comment by pennersr** [comment]
Perhaps to explain a bit more, my thoughts are:

- Most regular users are fully unaware of the +/. feature in email addresses. They may get confused if their email address gets normalized into something without dots.

- Well-willing tech-savy users that use the + to differentiate would become hindered by this.

- Not-so-well-willing tech-savy users are not stopped at all, they simply use meltmail, maildrop and so on.

- Google apps for domains are not recognized, and other providers do this as well (e.g. Outlook)

**Comment by lukeburden** [comment]
I was envisioning storing an additional "display" version of the email to avoid the user seeing the normalized case.

On the tech savvy user front - yep, they'd be hindered, but in my use case where the less savvy are the majority, I'd be inclined to do this to avoid the multiple account confusion that is so common amongst the less savvy.

Your point about Google apps is a good one! That does make it impossible to apply normalization in all Google mail cases. I'd guess though that the "gmail.com" and "googlemail.com" (another variation!) make up an overwhelming majority of Google addresses on most sites. Since this isn't about restricting people, rather helping them reduce confusion / increase likelihood of resolving a login/signup to an existing account, I'd be OK only targeting those two main identifiable domains.

Thanks for your thoughts Raymond. If you have any tips on reducing the occurrence of multi accounts beyond resolving accounts using provider verified emails, I'd love to hear them.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/366
