### ISSUE TITLE
ORCID provider: Add SCOPE to limit transferred data

### ISSUE THREAD

**Issue by johlton** [pennersr/django-allauth#3672]
It would be pretty cool to have a SCOPE for the ORCID provider, like in other providers, e.g. [Google](https://docs.allauth.org/en/latest/socialaccount/providers/google.html) or [Github](https://docs.allauth.org/en/latest/socialaccount/providers/github.html).

Right now, all public ORCID data like publications, work info etc. for an account is getting transferred to local database. In cases where one would only use the ORCID provider for authentication, this is not necessary. As a side note, this also might let ring alarm bells with GDPR officers in certain institutions (although I'm not an expert at all and it's publicly available data).

The scope should accept `orcid-identifier` and `person`, for example. 

What do you think? I had a look at the source code but I'm not sure how to implement this myself.

Thanks!

**Comment by pennersr** [comment]
You can already configure the `SCOPE` of the ORCID provider:

https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/orcid/provider.py#L22

https://github.com/pennersr/django-allauth/blob/main/allauth/socialaccount/providers/oauth2/provider.py#L38

**Comment by MyPyDavid** [comment]
we have the same issue, that the additional user data of the ORCID provider ends up in the `extra_data` field of the `socialaccount` instance, and I can't find a way to change it via the configuration of the provider.

the SCOPE that ORCID accepts (for OAuth) seems to be only the API action (like `/authenticate`), https://info.orcid.org/documentation/integration-guide/troubleshooting/#API_Errors.

I think the way to solve it, would be to add the `extract_extra_data` method to the `OrcidProvider` and maybe add a provider setting to select which attributes will be extracted.
Currently, the `extra_data` contains a dict with these keys `['orcid-identifier', 'preferences', 'history', 'person', 'activities-summary', 'path']
`

Do you think it would make sense to solve it this way? I could add a PR for the implementation when it seems necessary to include this.

**Comment by MyPyDavid** [comment]
Dear @pennersr, excuse me for posting on a closed issue, do you mind reading my comment?
It applies to this and I didn't want to open a duplicate. Thank you 🙏

**Comment by pennersr** [comment]
Sorry, but I don't understand the issue:

> we have the same issue, that the additional user data of the ORCID provider ends up in the extra_data field of the socialaccount instance, and I can't find a way to change it via the configuration of the provider.

What do you mean by "change it via the configuration" ? What's wrong with additional information being present in `extra_data`? In any case, I haven't personally used ORCID, so I am not familiar with the scopes and related data payloads it offers.

**Comment by MyPyDavid** [comment]
thanks for the reply! I'll try to clarify the issue.  
As a service provider we want to minimize the amount of personal user information that is stored in our application, and store only what is required for the service (GDPR interpretation).
Currently, when a user authenticates at ORCID via the `/authenticate` API scope it send the whole/complete user profile information to the service provider. I also do not understand why ORCID sends all this information but it is part of the users' public/member profile.

I think that confusion in this issue is now about the term "scope" and its meaning. As a service provider, I would think that the scope refers to the user's personal information attributes and that I can "select" these attribtutes by changing the scope.
The scope that the allauth `OrcidProvider` refers to is from the ORCID API scopes (https://github.com/ORCID/orcid-model/tree/master/src/main/resources/record_3.0#scopes) and is defined as `/authenticate`.
This is the scope for authentication, however it does not allow for the selection of which user data will be transferred and stored in the application. So, then all this user data ends up in the `socialaccount.extra_data` where it can be interpreted as "too much information" (even though it is sort of public information).   

To solve this issue for my service locally, I would overwrite the `OrcidProvider` and add the `extract_extra_data` to be able to select which keys from the data payload will be stored.
However, multiple service providers might (and seem to) have this same issue, it could make sense to include it in the allauth `OrcidProvider` to be able to select via the allauth settings (`SOCIALACCOUNT_PROVIDERS`) which attributes will be stored in the `extra_data`.
Would you agree or have any other suggestions for this?

Hope this clarifies it, thanks again for your time!

**Comment by pennersr** [comment]
> To solve this issue for my service locally, 

I would suggest you use the `pre_social_login()` adapter method. There, you can do e.g. `sociallogin.account.extra_data = {}` to wipe out any data stored, or filter as you see fit. That works with any provider, so you don't need to override `OrcidProvider`.

**Comment by MyPyDavid** [comment]
alright, thanks for the suggestion! I can implement this solution for my service and document this for our software project.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3672
