### ISSUE TITLE
Default setting for ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS (True) results in spam emails

### ISSUE THREAD

**Issue by longhotsummer** [pennersr/django-allauth#3794]
The default setting for `ACCOUNT_EMAIL_UNKNOWN_ACCOUNTS` is `True`. This means the default configuration of allauth is effectively happy to send spam reset emails to arbitrary email addresses.

I suggest this default is changed to `False`.

**Comment by pennersr** [comment]
But, if I signup using your email address, the system will happily spam you as well.  So, changing the default does not prevent spamming yet does break backwards compatibility.

**Comment by pennersr** [comment]
Closing -- would not solve an issue.

**Comment by jayqi** [comment]
I would like to add my voice here that this feels like a surprising default to me that I found problematic. I already dealt with spam signups by adding a captcha to my signup form, but I still ended up being flagged for spam because of random arbitrary email addresses being input into the password reset form. I would have rather this been a setting that required me to intentionally set it.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3794
