### ISSUE TITLE
Feature Request: Support for reCAPTCHA

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [pennersr/django-allauth#3802]
Hi @pennersr,
What are your thoughts of adding recaptcha in login and registration forms ?
I'm looking forward to work on this if you are planning integrate it with all-auth.

<https://github.com/django-recaptcha/django-recaptcha>

**Comment by pennersr** [comment]
The allauth forms can be easily extended, and it's really trivial to fully use django-recaptcha as is without redoing all of that work in allauth itself, and without making allauth dependent on django-recaptcha. We can add a recipe on how to do this to e.g. the docs (PR welcome), but as it is really just a few lines of code to connect the two, and because recaptcha is not the one and only solution, I would like to stay away from bringing this in scope. 

FWIW, I've used something like this in the past:

```
ACCOUNT_SIGNUP_FORM_CLASS = "foo.forms.FooSignupForm"

from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible

class FooSignupForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["captcha"] = ReCaptchaField(widget=ReCaptchaV2Invisible)

    def signup(self, request, user):
        pass
```

**Comment by pennersr** [comment]
Great. PRs to improve the documentation are always welcome, but I prefer to not keep issues open for these topics. So closing this.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3802
