### ISSUE TITLE
social_account_added signal not called

### ISSUE THREAD

**Issue by p-fruck** [pennersr/django-allauth#3834]
I am currently working towards implementing a group synchronization feature for InvenTree based on the sso `extra_data` attributes. I am trying to access the data on the first login and on each subsequent login to make sure the data is always up-to-date.

In the apps.py `ready` method, I am connecting my custom callback like this:

```
social_account_added.connect(ensure_sso_groups)
social_account_updated.connect(ensure_sso_groups)
```

But for some reason, the `ensure_sso_groups` method is only called for `social_account_updated`, the first creation of the social account does not seem to send a `social_account_added`. Is there anything I am missing?

**Comment by pennersr** [comment]
"Added" occurs when a social account gets connected to an existing local account, and "Updated" when an existing social account gets updated because a new login occurred, resulting in new data. Neither of those signals are triggered when an account gets created, as creation is not an add nor an update.

You can use `pre_social_login`, or in case you need to intervene at a later stage, just use the regular `user_logged_in`.

**Comment by p-fruck** [comment]
Thanks for clarification! Would you accept a PR to the docs highlighting this bevahior?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3834
