### ISSUE TITLE
is_existing not updating after saving a new user connected to SocialLogin

### ISSUE THREAD

**Issue by famoseagle** [pennersr/django-allauth#3870]
I'm unsure of the fix, but if you save a new user connected to a sociallogin, call sociallogin.is_existing, it returns False when it should be True. Maybe after line 275 in [socialaccounts/models](https://github.com/pennersr/django-allauth/blob/f6577fa0ff0060f1debb4dfe1103d8484aaea69c/allauth/socialaccount/models.py#L275) set `self.user = user`. Or clear the _is_existing flag. This bug currently breaks a dj_rest_auth flow. 

Alternatively, you could revert [this]( https://github.com/pennersr/django-allauth/commit/2021e0be8b7819916a1585ad3708e9139e227516) commit. The extra complexity might not be worth it.

**Comment by adrenaline681** [comment]
Not sure if this is related to this but since v0.63.1 there was a bug introduced when creating an account using social login (in our case Google Auth). 

The error that we are getting on first registration is the following:
```
User is already registered with this e-mail address
```

I can confirm that no user is registered with that email

@famoseagle the commit you are talking about was introduced on v0.63.1 so that's why im hinking it might be related.

For more information, we are using dj-rest-auth to interact with Allauth. 

I can confirm that this issue is not happening with Allauth v0.63.0

**Comment by pennersr** [comment]
`is_existing` is used just after the third-party handshake has taken place, before all the usual allauth login/signup machinery kicks in. A valid use case is to lookup e.g. an existing user at the  `pre_social_login()` adapter method, and assign that (`sociallogin.user = user_you_just_looked_up`). In that case, that commit is doing its job. What's not valid is to start saving a new `user` instance yourself. That means that you're signing up users bypassing all of the allauth machinery. So this looks like an issue in dj-rest-auth to me.

**Comment by famoseagle** [comment]
Ok. @adrenaline681, thanks for posting this issue on dj-rest-auth. I will add some color.

**Comment by Ahmadshoh** [comment]
Hi everyone,

I am currently experiencing this issue with version 0.63.6. Based on the previous comments, I am still unclear on whether this has been resolved or what specific steps I need to take to address the problem.

Could someone please provide more detailed information or guidance on how to resolve this issue?

Thank you!

**Comment by pennersr** [comment]
As mentioned, this issue surfaces when allauth is being bypassed on important flows:

> That means that you're signing up users bypassing all of the allauth machinery. So this looks like an issue in dj-rest-auth to me.

The issue started to appear when an optimization was done within allauth to cache the result of `is_existing`. While that is perfectly fine within allauth scope, apparently this is causing sufficient trouble upstream to reconsider that (relatively) unimportant optimization.

So that is reverted now: 2cc8f199

This should alleviate the issue. Having said that, upstream is still doing wrong things, but that is out of our hands here,

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3870
