### ISSUE TITLE
[Suggestion] Make it possible to patch `reverse()`

### ISSUE THREAD

**Issue by alexandernst** [pennersr/django-allauth#3892]
I'm currently using django-hosts, which allows me to split the features of my app in several subdomains (`account.myapp.com`, `api.myapp.com`, etc...). Because of this I must use django-hosts's `reverse()` method (eg: `reverse("some-route", host="api")`.

allauth is using django's `reverse()`, which generates paths (eg `/account/signup/`) instead of FQDNs (`account.myapp.com/account/signup`), which is problematic to deal with.

I propose a mew method to be added to the `adapter.py`. Something like:

```
from django.urls import reverse

def reverse(name):
    return reverse(name)
```

This way the `reverse()` method can be overridden.

**Comment by pennersr** [comment]
I must admit, I am not really fond of the approach they took with django-hosts:
- `reverse` is core Django functionality, any Django project is using that, and it is not feasible for all projects to have a pluggable reverse method.
- An adapter method is not sufficient, you would also need a custom `{% url ... %}` tag in the templates, complicating the templates as well.

All in all, I don't think it is a good idea to increase the complexity at allauth for this purpose. 

If you must use django-hosts, I would monkey patch the reverse method. You could e.g. check who is invoking the reverse (by inspecting the stack trace) and depending on that tweak the behavior. This approach would support any Django project.

**Comment by alexandernst** [comment]
Replying to your points in the same order:

* Sure, all projects that are used with Django and django-hosts will have the same issue, but this isn't to say that allauth shouldn't try to play nice with django-hosts. In fact, you already walked the extra mile and, as per your own code, you already tweak allauth to play nice with some other projects: https://github.com/pennersr/django-allauth/blob/7148c9e03956fc8db7fd193243bd03af3f83c38b/allauth/account/auth_backends.py#L52
* django-hosts already has a template tag, and since templates are overridable, I could override them and use django-hosts's tag.

I really don't think the complexity will be increased at all. We're talking about a diff patch that would look like this:

```diff
-from django.url import reverse, reverse_lazy

...
-self.passthrough_next_url(reverse("account_signup"))
+self.passthrough_next_url(get_adapter().reverse("account_signup"))
...
```

Monkey patching django and inspecting the stack trace is a terrible idea for a variety of reasons and it really isn't a solution.

**Comment by pennersr** [comment]
While django-hosts has a template tag, allauth does not, and it cannot become dependent on django-hosts. Meaning, either allauth needs to provide one itself, or, we have a solution that only goes half way (adapter method that is not called at all times by allauth). Monkey patching is definitely not pretty, but it would get the job done.

**Comment by alexandernst** [comment]
Allauth doesn't need to depend on django-hosts nor implement a template tag. The templates of allauth are expected to be copied / overridden:

https://github.com/pennersr/django-allauth/blob/8f653fe7afe76848cfd26e8e80b738955a1aa372/docs/common/templates.rst#L10-L11

Once the developer has copied the templates to his own project, he can use django-hosts's tag. For example, the login.html template (https://github.com/pennersr/django-allauth/blob/8f653fe7afe76848cfd26e8e80b738955a1aa372/allauth/templates/account/login.html) could be modified like this:


```diff
{% extends "account/base_entrance.html" %}
{% load i18n %}
+{% load hosts %}
{% load allauth account %}
{% block head_title %}
...
...
...
-             {% url 'account_login' as login_url %}
+             {% host_url 'account_login' host 'api' as login_url %}
...
...
...
```

This patch would be applied in the templates that the developer has copied to his project; allauth shouldn't have to be patched.

**Comment by pennersr** [comment]
> The templates of allauth are expected to be copied / overridden

That is not / no longer true. The templates have been architected so that they are fully reusable and styleable, without altering them. 

But really, going for a solution that even within allauth scope would only partially work is not a viable solution. There are multiple points I see wrong with this:

- As discussed, the templates wouldn't be addressed.
- It is not only `reverse`, but also class based views `success_url` needs to be tackled, which uses `reverse_lazy`.
- Then there are Django settings like `LOGIN_REDIRECT_URL` which accept a urlname, which Django implicitly reverses.

So, providing an adapter method just for reverse would simply not work properly throughout the whole of allauth/Django. And even if we go all the way and fix these cases, then only allauth is addressed but the next app you are using in your project would still use a (hardcoded) reverse.

Monkey patching, while looking ugly, is quite effective. Something like this would solve all of the above:

``` python
# Warning, untested, just sketching code here...
from django import urls
from allauth.core import context
from django_hosts.resolvers import reverse

orig_reverse = urls.reverse
def my_reverse(*args, **kwargs):
   if context.request.path.startswith("/accounts/"):
     app = "allauth"
  elif context.request.path.startswith("/blob/"):
    app = "blog"
  reverse(...use app...)

urls.reverse = my_reverse
```

That would just be a 10-20 lines or so monkey patch which works universally, versus going over all `reverse()` calls, changing all `success_urls`, altering all the templates, and so on and ending up with an allauth only "solution".

So the real problem is that django-hosts went for a solution that requires every project to adapt to a new way of using Django core functionality, and I really do not want for allauth to make up for this by offering half a solution to the problem.

**Comment by alexandernst** [comment]
> That is not / no longer true.

I beg a pardon if that is the case, I was just stating your own docs.

> The templates have been architected so that they are fully reusable and styleable, without altering them.

This is arguably not true. There isn't a single class in the templates, I hardly can imagine how one would apply any advanced / complex styling just by targeting html elements instead of using class names (let alone that the structure itself can't be altered only via css).

But even accepting both statements, as I stated in my last comment, people that are not using django-hosts won't be forced to copy any of the templates as everything would keep working as-in. Only people that are using django-hosts would need to copy the templates and load the hosts tag (see my previous comment). I believe this addresses your first point about templates not being addressed.

Your second point is true, `reverse_lazy` would also need to be moved to `adapters`, but this is just a couple extra lines on top of the patch in my previous comment. Complexity would still be same.

[LOGIN_REDIRECT_URL](https://docs.djangoproject.com/en/5.0/ref/settings/#login-redirect-url) accepts both urlname **and** a full url, which is what people who use django-hosts usually use.

> even if we go all the way and fix these cases, then only allauth is addressed but the next app you are using in your project would still use a (hardcoded) reverse

Imho this really doesn't matter. Making allauth play nice with django-hosts has nothing to do with other libraries not playing nice with django-hosts. I don't think this problem should be thread as `either-or`.

I can't really understand your monkey patching POC. Is `context` some per-thread global variable-like pointer? How would that play with async requests and multiple threads in daphne?

> So the real problem is that django-hosts went for a solution that requires every project to adapt to a new way of using Django core functionality

I think django-hosts did the only thing it could to implement what they implemented. Every project having to adapt to a new way of using `reverse` is a totally expected thing. There just isn't any other way around having multiple subdomains and not having to specify which subdomain "you" want to use in order to reverse a urlname.

> and I really do not want for allauth to make up for this by offering half a solution to the problem

I still don't think providing a way to hook custom code for `reverse` (and `reverse_lazy`) in the `adapters` is half a solution as I still don't see what would be missing. Would it help if I created a demo project / POC or maybe a set of patches for this proposal?

**Comment by pennersr** [comment]
> I beg a pardon if that is the case, I was just stating your own docs.

Whether or not to fork the templates is the right approach depends, both ways are documented over here: https://docs.allauth.org/en/latest/common/templates.html

> Is context some per-thread global variable-like pointer? How would that play with async requests and multiple threads in daphne?

Sort of, yes -- `context.request` simply exposes the current `request` using a `ContextVar` which works in async and threading environments as well.

>  think django-hosts did the only thing it could to implement what they implemented.

Must admit, haven't given this much thought, and not at all familiar with django-hosts, but it would certainly be possible for django-hosts to monkey patch `reverse` and offer a `@host("api")` decorator or `with host("api"):` context manager that could be applied to existing Django views/code so that existing code would not need to be altered at all.

> Would it help ...

Honestly, I think it is quite clear even without a PoC what the impact of a change like this is -- all calls to `reverse()`, `reverse_lazy()`, `{% url ... %}` would be impacted, which is something I really do not like to take on given the reasons mentioned above. Really, those 10-20 lines I pasted above are just as effective, work with other projects as well, and does not litter non-standard `reverse()` calls all across the code base.

**Comment by alexandernst** [comment]
Fair enough

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3892
