### ISSUE TITLE
Unable to authenticate using `X-Session-Token`

### ISSUE THREAD

**Issue by KienTPhan** [pennersr/django-allauth#3981]
Hello,
I'm currently using `django-allauth==0.63.6` with the allauth.headless app. I noticed that I'm unable to successfully use `http://localhost:8000/api/_allauth/app/v1/auth/session` using the header `X-Session-Token`. I'm currently getting `401`. If I use the cookies + csrf header with the same `sessionid`, I would get the expected 200 response with `is_authenticated=true`.

**request using `X-Session-Token`:**
<img width="701" alt="image" src="https://github.com/user-attachments/assets/1a7c475c-7633-42ab-8498-6bad745ae463">
<img width="706" alt="image" src="https://github.com/user-attachments/assets/0766e4ca-3772-4a43-bfac-835af22359c9">

**request using cookie + csrf:**
<img width="691" alt="image" src="https://github.com/user-attachments/assets/c63ad010-717d-4ad6-9fb4-3c8b7e903077">
<img width="702" alt="image" src="https://github.com/user-attachments/assets/815d79c4-fc3f-493a-8484-7f83a940dd41">

**Comment by pennersr** [comment]
It's difficult to assess what is going on in your project. Can you try setting a breakpoint here?:

https://github.com/pennersr/django-allauth/blob/main/allauth/headless/internal/authkit.py#L51

Even if you send cookies to the `app` endpoints, they should be ignored as `request.session` is blank there. A few lines down you'll see the lookup of the X-Session-Token. Hopefully, by stepping through that code you'll find the cause of what is going on...

**Comment by KienTPhan** [comment]
I'll dig into it, thank you.

**Comment by neoromantic** [comment]
Just came to say that I have same issue. Investigation, but exactly the same.

All's working well, i can authorise, i get new session token, it's being save to database, but when i provide it via headers, i just get 401:

```
curl -k -H "x-session-token: p1z9vs0tg4uluy6soi9tfb5kxxqnghj1" https://localhost/_allauth/app/v1/auth/session
{"status": 401, "data": {"flows": [{"id": "login"}, {"id": "signup"}, {"id": "provider_token", "providers": ["google"]}]}, "meta": {"is_authenticated": false}}%                    
```

**Comment by neoromantic** [comment]
So I did some debugging and it seems to me that something is strange in allauth.headless..

Here we are as AnonymousUser: https://github.com/pennersr/django-allauth/blob/c76e9fbd3b03e16d272a9f0d0f69ba762e03812a/allauth/headless/internal/authkit.py#L51

Which seems to be OK, because we are anonymous and actually trying to access api with x-session-token header. 

I couldn't find any code that would even read from usersessions.user_id field in database to the request object. 

As it seems to me, there's no way it can work at all. It feels allauth expects user to be authenticated before even starting to actually authenticate him from the header. 

Or maybe I'm stupid.

**Comment by neoromantic** [comment]
Again, just sharing. Spent 1.5 hour, read through code, went with debugger, for the love of me I can't understand how it's even supposed to work. 

I mean, request.user is Anonymous, thus is_authenticated is false, thus AuthenticatedReponse returns 401. 

I really hope that some of the smarter than me people would take a look. Af of now, I can't figure out a way to (for example) change a password with x-session-token.

**Comment by pennersr** [comment]
> I couldn't find any code that would even read from usersessions.user_id field in database to the request object.

We start out with a blank session here:

https://github.com/pennersr/django-allauth/blob/main/allauth/headless/internal/authkit.py#L51

Here, we replace that blank session with the session being pointed to by x-session-token:

https://github.com/pennersr/django-allauth/blob/main/allauth/headless/internal/authkit.py#L60

Then, given that Django evaluates `request.user` lazily, the user ID is taken from the session (the one pointed to by the token).

**Comment by pennersr** [comment]
You can try this using the example app running over at https://react.demo.allauth.org

1. Make sure you are logged in there
2. Use the browser network inspector to copy the value of the session cookie
3. In a shell, run: `curl --header 'X-Session-Token: hpz(sessionid)hn8n1xlj8o'  https://react.demo.allauth.org/_allauth/app/v1/auth/session`
4. You'll see a `{"status": 200, "data": {"user":...` response, confirming that authentication using a x-session-token works.

**Comment by pennersr** [comment]
There is little that can be done on this end. This functionality is covered in the test suite, and is shown to be working in the example app (see my previous comment). So, I would suspect there is something additional going on in your own project. Try stripping down e.g. additional middleware that you might have running to find the cause. If you do find something that points to an issue in allauth, just reopen.

**Comment by KienTPhan** [comment]
I haven't had time to dig deeper to find a solution but I found out the cause for my project. So I have a Timezone middleware here:
```python
class TimezoneMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        if request.user.is_authenticated:
            user_timezone = request.user.timezone
            if user_timezone:
                timezone.activate(pytz_timezone(user_timezone))
            else:
                timezone.deactivate()
        else:
            timezone.deactivate()

        return self.get_response(request)
```

The line ` if request.user.is_authenticated:` accesses the user model which is at this point an Anonymous user and somehow causes the request to 401. If I remove this middleware, the request returns 200 as expected.

Here is the order of MIDDLEWARE in settings.py
```python
MIDDLEWARE = [
    ...
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "spendingtracker.middleware.timezone_middleware.TimezoneMiddleware", 
]
```

Note: when I send in csrf and sessionId cookies, I actually get a user on line  ` if request.user.is_authenticated:`  in my TimezoneMiddleware. It seems like request.user is not set to the actual user before it hit middlewares placed after "django.contrib.auth.middleware.AuthenticationMiddleware".

**Comment by neoromantic** [comment]
Found my problem. Similar to @KienTPhan, it's been something that touched request.user, in my case - Posthog.

**Comment by pennersr** [comment]
Thanks @KienTPhan, that indeed points to an issue in allauth. I managed to reproduce it -- will be fixed.

**Comment by pennersr** [comment]
Fixed via 301324e3

**Comment by avmturo** [comment]
Was unsure if I should open a new issue or just comment here. I am having an issue, which I thought originally might be the same outlined here, but I upgraded to the version in which this was patched, but still running into an issue with using the X-Session-Token to validate an app session:
I have a simple test, which worked fine in 'browser' mode, updating to 'Client.App' and adding the x-session-token header has caused an issue I am trying to debug:

The test is super simple:
` def test_login_success(self):
        login_resp = self.client.post(
            reverse("headless:app:account:login"),
            {
                "email": self.email,
                "password": self.password,
            },
            content_type="application/json",
        )
        self.assertEqual(login_resp.status_code, 200)
        ...
        self.assertTrue(login_resp_meta.get("is_authenticated"))
        session_token = login_resp_meta.get("session_token")
        headers = {"X_SESSION_TOKEN": session_token}

        session_resp = self.client.get(
            reverse("headless:app:account:current_session"),
            content_type="application/json",
            headers=headers,
        )
        self.assertEqual(session_resp.status_code, 200)`
        
        I did some debugging, and thought I could get some help on what I might be missing here, the login works great, and the request is successfully being made with the token header, In debugging everything goes great until a certain point, which I am trying to understand:
        We get here and the token is properly retrieved from the request:
        
<img width="919" alt="image" src="https://github.com/user-attachments/assets/47f433d3-ea5a-4167-85ca-40ef78ddab36">

Then through the auth context it looks fine, the session is properly set to the `request.session`:
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/5438380e-825e-4ac5-9a03-e26adb3b2ba3">

The issue, I think, seems to be in what comes next, when `expose_session_token` is called by, `_add_session_meta`:
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/937f8981-5275-42de-b0b3-82b4c5bd81e3">

With `modified = False` and `empty = False`, there is nothing returned by this function, and then meta here is returned without a token, should we always expect (if things are going as they should), modified to be true by this point?:
<img width="916" alt="image" src="https://github.com/user-attachments/assets/a1e0fabf-6c73-4ded-b2ce-594d67a83258">

This meta is returning with just:
`{is_authenticated = False}`, and no session_token, since it was not returned by`expose_session_token` as modified was false.

Apologies for the long post, I might be missing something obvious here, but any feedback would be great.

**Comment by avmturo** [comment]
> Then, given that Django evaluates `request.user` lazily, the user ID is taken from the session (the one pointed to by the token).

Looking more into this, I still don't see when this occurs. 
```
    old_user = request.user
    old_session = request.session
    try:
        request.session = sessionkit.new_session()
        purge_request_user_cache(request)

        strategy = app_settings.TOKEN_STRATEGY
        session_token = strategy.get_session_token(request)
        if session_token:
            session = strategy.lookup_session(session_token)
            if not session:
                raise ImmediateHttpResponse(UnauthorizedResponse(request, status=410))
            request.session = session
            purge_request_user_cache(request)
        request.allauth.headless._pre_user = request.user
        # request.user is lazy -- force evaluation
        request.allauth.headless._pre_user.pk
```
        I see us evaluate always to the request.user, but don't see us every update request.user with the user from the session

**Comment by avmturo** [comment]
Just a final update, as @pennersr mentioned, I took a look at the middleware:
# "django_otp.middleware.OTPMiddleware", is causing the issue, and removing it makes all tests pass in both browser and app mode.

**Comment by pennersr** [comment]
@avmturo Are you using version 64+ of allauth? 0.63 contained an issue where touching `request.user` in a middleware caused issues, but those should have been fixed. So, if this still occurs with version 64, I am wondering what is the cause of that...

**Comment by pennersr** [comment]
> I don't see where we use the session to update the request.user

You won't find that in allauth code. `request.user` is not a plain property, it actually invokes a function that extracts the user from the session. So, you won't find any code within allauth setting the user, what you do see is allauth setting the session, and, clearing the cached `request.user` data so that touching `request.user` reevaluates the value.

**Comment by avmturo** [comment]
> > I don't see where we use the session to update the request.user
> 
> You won't find that in allauth code. `request.user` is not a plain property, it actually invokes a function that extracts the user from the session. So, you won't find any code within allauth setting the user, what you do see is allauth setting the session, and, clearing the cached `request.user` data so that touching `request.user` reevaluates the value.

Yup, figured that out eventually. Thanks for the response! I am on version 64 and have confirmed I have this commit 
https://github.com/pennersr/django-allauth/commit/301324e3ed2bf7c95987f24625ee8ebd7480ce85 in my packages. 
The specific middleware causing the issue was the 
`django_otp.middleware.OTPMiddleware`, removing it makes my tests pass, have double checked adding only it backs causes the failure I originally outlined. About to log off, we don't need the middleware anyways, but can have a look tomorrow to see if I can figure out exactly why this middleware is causing issues.

**Comment by pennersr** [comment]
I checked the OTP middleware, and this is the problematic part:

``` python
    def __call__(self, request):
        user = getattr(request, 'user', None)
        if user is not None:
            request.user = SimpleLazyObject(
                functools.partial(self._verify_user, request, user)
            )

        return self.get_response(request)

    def _verify_user(self, request, user):
        """
        Sets OTP-related fields on an authenticated user.
        """
        user.otp_device = None
        user.is_verified = functools.partial(is_verified, user)
```

So, it basically patches `request.user` to point to its own logic, where `request.user` is not re-evaluated (as it is passed as an argument to `partial()`).

Now, I don't see a proper solution here. Even if allauth were to directly set `request.user`, that would likely get x-session-token working, but it would completely bypass the custom `request.user` set by that middleware, meaning, we would have a middleware intentionally adjusting `request.user` which allauth would disrespect, which is also wrong. Likely, the only way to truly make this compatible is for Django OTP to alter their middleware to keep on evaluating lazily.

**Comment by Hammedolatunji** [comment]
@pennersr I am having similar issue where request.user.is_authenticated returns false with a valid X-Session-Token sent in the header whenever a request is sent to other part of the app apart from those url provided by allauth and headless. I am new to Django and in fact, this is my first Django project. I might be missing some things but haven't found solution elsewhere.

I used custom user via CustomAccountAdapter which extends allauth.account.adapter.DefaultAccountAdapterby overriding the save_user function as digested from the documentation. I defined custom token strategy to generate access_token and refresh token while copying the implemention of session token from all:

```
from allauth.account.adapter import DefaultAccountAdapter
from users.models.user_profile import UserProfile
from allauth.account.utils import user_email, user_username

import json

class CustomAccountAdapter(DefaultAccountAdapter):
        
    def save_user(self, request, user, form, commit=True):     
        data = json.loads(request.body)
        email = data.get("email")
        username = data.get("username")
        user_email(user, email)
        user_username(user, username)
        if "password" in data:
            user.set_password(data["password"])
        else:
            user.set_unusable_password()
        self.populate_username(request, user)
        user.is_creator = data.get('is_creator', False)
        if commit:
            # Ability not to commit makes it easier to derive from
            # this adapter by adding
            user.save()
            if data.get('birth_date', False):
                UserProfile.objects.create(user=user, birth_date=data.get('birth_date', None))        
                        
        return user
```

I have a custom middleware where I want to block unauthenticated request from accessing some route patterns but the middleware could not get request.user

```
from django.http import JsonResponse
from django.utils.deprecation import MiddlewareMixin

class BlockAnonymousUsersMiddleware(MiddlewareMixin):
    def process_request(self, request):
        print(request.user)
        protected_paths = ['/api/']
        for path in protected_paths:
            if request.path.startswith(path) and not request.user.is_authenticated:
                return JsonResponse({
                    'status': 401,
                    'errors': [{'message': 'Authentication required'}]
                })
```
                
 Here is the middleware used in the app as contained in settings.py
```
 MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'users.middlewares.BlockAnonymousUsersMiddleware',
]
```

**Comment by pennersr** [comment]
@Hammedolatunji That is to be expected. The X-Session-Token is not automatically handled elsewhere in the stack. If you're using django-rest-framework, you'll e.g. need to add an authentication class that understands and looks up that token.

**Comment by Hammedolatunji** [comment]
Thanks. I eventually used JWToken defined in token strategy and relied on access token and refresh token.

**Comment by DDevine** [comment]
I have a JWT strategy and when you have browser-flow social auth you need to exchange a session for a token. I wanted to use `auth/session` to get access to `meta.access_token` that the headless OpenAPI docs indicate should be present, but it is not present due to https://github.com/pennersr/django-allauth/blob/b74b04a8261486db8a3823c26c188820aed599aa/allauth/headless/internal/authkit.py#L82 

I know this is a different issue, but I am seeing the same issue demonstrated in the screenshots above and other people mentioning they have a JWT token strategy so its a usecase that may need addressing.

I've hacked around it for the time being (I have a custom refresh_token endpoint that I have allowed Session auth to use) but it would be nice to just use the documented API.

(I tried signing up to codeberg despite my aversion to that organisation, but got a 500 error...)

**Comment by czue** [comment]
In case anyone else runs into this issue, `django-hijack` has a similar problem to the [one mentioned here](https://github.com/pennersr/django-allauth/issues/3981#issuecomment-2284721164). [This is the problematic part](https://github.com/django-hijack/django-hijack/blob/master/hijack/middleware.py#L24-L29):

```python
class HijackUserMiddleware(MiddlewareMixin):
    # other stuff here
    def process_request(self, request):
        """Set `is_hijacked` and override REMOTE_USER header."""
        user = copy.copy(request.user)  # prevent recursion error
        request.user = SimpleLazyObject(lambda: self.setup_user(request, user))
        if "REMOTE_USER" in request.META and request.user.is_hijacked:
            request.META["REMOTE_USER"] = request.user.get_username()
````

I haven't found a workaround yet, but guessing it involves a similar need for the library itself to lazily reference the user object.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/3981
