### ISSUE TITLE
Bearer Token fails to authenticate django rest api endpoints

### ISSUE THREAD

**Issue by nouaim** [pennersr/django-allauth#4018]
Hello, I am retrieving a bearer token from the front-end (angular) using google oauth and then i send it in the headers but this didn't authenticate django rest api endpoints, because allauth authentication seems to use a **session id** instead , do you have an idea to make the oauth working with the bearer token instead of session id? 

![Screenshot from 2024-08-07 12-21-42](https://github.com/user-attachments/assets/8e0c8e9f-a6b2-49fa-b1f3-586d13da88b4)

**Comment by pennersr** [comment]
If a token is received on the frontend, then that token must be passed to the backend so that the backend can turn that into an active session. The endpoint for that is:

https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Providers/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1provider~1token/post

Also checkout the demo over here:

https://react.demo.allauth.org/account/login

When you enable the Google One Tap sign-in, this flow is triggered (frontend token is passed on to backend).

**Comment by nouaim** [comment]
@pennersr thanks for the fast reply, I am checking that

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4018
