### ISSUE TITLE
Verifying current session, does not return new tokens

### ISSUE THREAD

**Issue by avmturo** [pennersr/django-allauth#4048]
I have headless allauth almost fully working for my app, just am running into an issue with getting new tokens. I have my own token strategy, using simpleJWT for DRF. Login and all this works fine, but given the lifetime of the JWTs, I would like to get a new token upon verifying the session. 
The docs show that, like login and register, the access tokens should be returned in the meta for verifying a session:
https://docs.allauth.org/en/latest/headless/openapi-specification/#tag/Authentication:-Current-Session/paths/~1_allauth~1%7Bclient%7D~1v1~1auth~1session/get

I however am not getting this in the response, I get the 200 response (using the x-session-token in my headers). But no token data is returned in the meta:

<img width="555" alt="image" src="https://github.com/user-attachments/assets/3fca5b1e-d487-45d1-ad5f-0225ba5f35e1">

**Comment by pennersr** [comment]
> the access tokens should be returned in the meta for verifying a session

I can see why one can come to to that conclusion  as the example includes that in its response. Though, in the response the access token is optional, so that is not guaranteed.  Currently, the access token is only returned if the user transitions from not-authenticated to authenticated.

Possibly, that needs to be changed to return an access token if the user transitions from not-authenticated to authenticated, OR, no access token is passed to the endpoint.

**Comment by avmturo** [comment]
@pennersr Yup! This was the same conclusion we came to. Keep the refresh token / access token at the app level, separete from the allauth session token/logic

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/4048
