### ISSUE TITLE
Django Site Framework

### ISSUE THREAD

**Issue by theduke** [pennersr/django-allauth#457]
On a fresh installation, when migrating with south after syncdb, 
the command fails with 

"CommandError: One or more models did not validate:
socialaccount.socialapp: 'sites' has an m2m relation with model <class 'django.contrib.sites.models.Site'>, which has either not been installed or is abstract."

I have no interest in using the django.contrib.sites app!

0.14.2

**Comment by davidrenne** [comment]
@theduke why no interest in using it?  Just curious.

Cant you just install the tables and then just use SITE_ID = 1 in your settings.py?

How can it negatively affect things by installing the dependency.

Sent pull request for clarity that sites is required.

**Comment by iMerica** [comment]
> How can it negatively affect things by installing the dependency.

Sites ==  configuration to the database. This forces us to choose from a bunch of nasty options:

- Manually create a site object in the Django admin every time we need to deploy Django somewhere new. For many of us doing headless, DRF Django work, this is incredibly burdensome because we intentionally don't want a Django Admin.
- Manually run a shell script.
- Write a custom init script that creates the site.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/457
