### ISSUE TITLE
JSON extra_data could be stored in a JSON native column if in PostgreSQL 9.3+

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [pennersr/django-allauth#598]
If the database is PostgreSQL 9.3+, social graph extra_data column could use the native JSON data type. Just override the JSONField (socialaccount/fields.py) db_type method with:

def db_type(self, connection):
        if connection.vendor == 'postgresql' and connection.pg_version >= 90300:
            return 'json'
        else:
            return super(JSONField, self).db_type(connection)

OR, maybe, just replace the whole field with https://github.com/bradjasper/django-jsonfield

Thanks!

**Comment by jleclanche** [comment]
@pennersr I want to share how we're doing it in dj-stripe: https://github.com/dj-stripe/dj-stripe

File in question:
https://github.com/dj-stripe/dj-stripe/blob/master/djstripe/fields.py

```py

from .settings import USE_NATIVE_JSONFIELD


if USE_NATIVE_JSONFIELD:
    from django.contrib.postgres.fields import JSONField
else:
    from jsonfield import JSONField

...

class StripeJSONField(StripeFieldMixin, JSONField):
    pass
```

So all our JSONFields in stripe subclass either jsonfield.JSONField or django.contrib.postgres.fields.JSONField.

It is safe to do this in allauth, because allauth requires Django 1.11 which has the native JSONField. Hiding this behind an opt-in setting makes it possible for postgres user to opt into this without being forced to, which means the next version of allauth that implements this won't require a painful migration.

The migration step however *is* painful and we haven't implemented it in dj-stripe. I think it's fair to tell people "Do it yourself, or contribute it to allauth, or start from scratch with the setting" as long as it's well-documented.

Incidentally, the latest version of django-jsonfield isn't compatible with django 2.0 (https://github.com/dmkoch/django-jsonfield/issues/210) and is erroring in some places, including the social admin :(

**Comment by pennersr** [comment]
Closing in favor of moving to #2599

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/598
