### ISSUE TITLE
Unable to access request.GET['next'] in get_login_redirect_url 

### ISSUE THREAD

**Issue by ninajlu** [pennersr/django-allauth#670]
My form submits as follows 

form class="form-signin" role="form" action="{% provider_login_url "facebook" method="js_sdk" next="/next"%}"

I overrided the DefaultAccountAdapter with my own AccountAdapter with method 
def get_login_redirect_url(self, request):
		print request.GET['next']
		...

But request loses the next parameter and the print returns an error because there is no "next" in request.GET.
Why can't I access the next parameter?
I was originally using get_login_redirect_url to handle different url redirects after creation of social versus username/password users. Now, I need to be able to specific the next parameter in the URL for another variant of behavior for social user login but am unable to access the next parameter because it does not seem to be passed.

**Comment by teolemon** [comment]
I'm facing the same issue. I'd like to get the ability not to hardcode the url into the provider_login_url tag.

**Comment by huangtao800** [comment]
I came across the exact same problem.

**Comment by pennersr** [comment]
The `next` parameter is passed on to e.g. `/accounts/google/login/?next=/foo/`. Then, the OAuth2 handshake takes place, and after completing that you end up at `/accounts/google/callback/`. At this stage, the request is filled with OAuth2 handshake parameters, which explains why `next` is not there.

The next URL `/foo/` is preserved during the handshake, which is why you'll properly end up at `/foo/` after all of this.  You can access the redirect_url via `sociallogin.get_redirect_url()`.  Currently, the `sociallogin` is not available in the adapter `login` method, but you could access it via the `pre_social_login` signal/adapter method.

**Comment by greenstatic** [comment]
I was experiencing the same issue however I have not setup OAuth2 (local accounts only). I have a potential hackish workaround:

```
import urllib.parse as urlparse
from django.utils.http import is_safe_url

try:
  url = request.META['HTTP_REFERER']
except KeyError:
    pass

 if url:
   parsed = urlparse.urlparse(url).query
   params = urlparse.parse_qs(parsed)

    try:
      if is_safe_url(params['next'][0]):
        return params['next'][0]

    except KeyError:
      pass
```

**Comment by pennersr** [comment]
See my comment

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/670
