### ISSUE TITLE
Allow easier styling using appropriate markup in account/login.html template

### ISSUE THREAD

**Issue by bittner** [pennersr/django-allauth#678]
The markup in the login template [account/login.html](https://github.com/pennersr/django-allauth/blob/master/allauth/templates/account/login.html) makes flexible styling hard, currently.

For example, how do you easily place the list of social accounts, the separating "or" text, and the user/password based login form next to each other, allowing them to wrap when the screen gets more narrow? The social accounts list, "or", and the login form should then ideally be stacked from top to bottom. This is hard to do, e.g. using Twitter Bootstrap, when a `div` is missing that surrounds the three blocks (which would take a `row` class in Bootstrap).

I'd suggest to surround the three blocks by a `<div class="allauth_login_form">` and `</div>`, starting after the introductory `<p>...</p>` text paragraph. A result could look like this: http://demo.organice.io/login/ (sorry, still a bit ugly!)

Would you accept a pull request for this?

**Comment by velis74** [comment]
I must say that the only thing I missed when I went about styling default templates, were the IDs marking position of form elements.

Otherwise, I was able to style (jQuery UI) allauth templates by overriding **only** `base.html`. 15 lines of jQuery UI code and a bit of CSS. This actually styles **ALL** templates, so I was really happy with the effort involved and result obtained.

So, current solution **IS** quite capable of being styled already.

If there's interest, I can submit a patch with my solution, but I'd need @pennersr to tell me where I might do that.

**Comment by MasterKale** [comment]
@velis74 Could you expound a little bit on how you were able to style everything with just a bit of JQuery and CSS? I'm currently dreading going through and customizing every single allauth template, but I can't think of a better way to wrap these templates in custom styling since there aren't any allauth-specific classes I can override with CSS or query for with Javascript.

**Comment by velis74** [comment]
[This](https://drive.google.com/open?id=0B1Iq8o-lD8RUSzRnOXlVWExhX2M) is my `base.html`, stored in `templates/account/base.html`.

Additionally, I have the social logos stored in `static/account/`, all named according to the social app in question. See lines 143 - 147 in `base.html`.

**Comment by derek-adair** [comment]
i feel like an old man... I remember when allauth didn't have ANY templates and I was moaning about it to you like 10 years ago.

ANYWAYS... close this as welcoming a PR and move on.  It's not worth debating users over semantics for something that is intended for convenience.  We could go down the rabbit hole of opinions about UI standards and blah blah blah all day.

-------
To give the advocates for an out-of-the-box functioning auth system an olive branch -- **This is something worth considering in a more organized and concerted effort.**  This would be a major change in the original intention of this project which was very clearly not meant to be an plug-n-play solution.

**Comment by derek-adair** [comment]
Also this is sooo old.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/678
