### ISSUE TITLE
HTML email template

### ISSUE THREAD

**Issue by nordbit** [pennersr/django-allauth#682]
Sending confirmation html template dosent work for me. 
I create custom HTML template according to http://django-allauth.readthedocs.org/en/latest/advanced.html#sending-e-mail but only txt template is send to user

**Comment by bufke** [comment]
Leaving a message here for others. I ended up having to run a debugger to figure this out.

The docs say use `account/email/email_confirmation_message.html`

However it needs to also include `account/email/email_confirmation_signup_message.html`

I believe the signup one happens only on a new user account - however for many use cases both should be the same.

txt works because there is always a txt template even if you don't customize it.

**Comment by pythonoma** [comment]
@bufke answer should be added to the docs

**Comment by nznelson** [comment]
I believe this is still missing from the docs: http://django-allauth.readthedocs.io/en/latest/advanced.html

**Comment by cchacholiades** [comment]
Where does the `account/email/email_confirmation_message.html` being used? On account signup it is clearly using this template `account/email/email_confirmation_signup_message.html`?

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/682
