### ISSUE TITLE
Make allauth more ajax-friendly

### ISSUE THREAD

**Issue by pakal** [pennersr/django-allauth#799]
I plan to use django-all auth for a completely "webservice" use cas, i.e signup/login/logout via Ajax.

Signup works well, but login, logout and other views are very html-centric, issuing redirections instead of json responses for most functional cases.

Before I begin reworking these views to make them ajax-friendly, I'd like to know: would such evolutions be accepted for merging ? Are there some caveats I should be aware of ? Or is there a django-allauth-like lib which would be more relevant for ajax workflows (django-user-accounts is not one of them alas...) ?

Thanks,
regards, 
Pakal

**Comment by pennersr** [comment]
Most allauth views are already AJAX capable, even handing over redirects thu JSON data. If you have concrete issues or suggestions for improvement, feel free to reopen this ticket.

**Comment by jamesbrobb** [comment]
I'm also seeing this issue on version 0.19.1.

Due to the order (and implementation) of ``RedirectAuthenticatedUserMixin`` and ``AjaxCapableProcessFormViewMixin`` on ``LoginView`` and ``SignupView``, if the user's already logged in when an AJAX request is made, a ``HttpResponseRedirect`` is returned instead of the correct AJAX response.

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/799
