### ISSUE TITLE
Stay on same page on login

### ISSUE THREAD

**Issue by SiddharthMantri** [pennersr/django-allauth#854]
I'm using `allauth`'s Facebook login feature in my templates as follows:

    {% load socialaccount %}
    {% providers_media_js %}
    <li><a href="{% provider_login_url "facebook" method="js_sdk" %}" class="navbar-txt-block">Login With Facebook</a></li>

This handles login on the same page instead of redirecting to `/accounts/login`. However, I'm not able to write a method such that on login, the user stays on the current page itself instead of redirecting to `LOGIN_REDIRECT_URL`. I've asked on StackOverflow as well but I've not got any answer. Any suggestions for this?

**Comment by bsmartt13** [comment]
Have you tried taking advantage of the ?next="<current_path>" parameter?  That's intended specifically to override LOGIN_REDIRECT_URL, in cases you don't want to take the user to LOGIN_REDIRECT_URL.

The behavior you're describing is how allauth is supposed to work.  How could allauth possibly know what you're intending to do?

**Comment by pennersr** [comment]
Currently, this is not supported. After retrieving a token from FB via Javascript that token is posted to the server. After that, several scenario's are possibly, ranging from being simply logged in to being blocked because you need to verify your email address. All these flows are handled server side, via redirects, forms, etc. So staying on the same page is not possible that way.  You could fork fbconnect.js and alter its onLoginSuccess method to asynchronously post the token and stay on the same page, yet dealing with all the use cases that allauth has to handle will be difficult as you have to handle these client side. Still, if your project requirements are such that the login always succeeds as you do not verify email et al, you might get away with this that way...

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/854
