### ISSUE TITLE
Hardcoded capitalisation of default template headings and buttons

### ISSUE THREAD

**Issue by fmalina** [pennersr/django-allauth#867]
A lot of unnecessary overriding of default templates is to do with capitalisation preference for headlines and buttons. I noticed it in my project and other customised templates in the wild. Ideally the default templates would only capitalise the first letter of the element and leave the title casing to CSS.

    h1, button { text-transform: capitalize }

Is there a specific reason they are titlecased apart from typographic preference, such as string canonicalisation for l10n? I don't think it's case sensitive.

**Comment by pennersr** [comment]
Ideally, template content looks good without any CSS at all. So that's why titles are capitalized as titles are supposed to. If that does not match your preference, you do not need to alter all templates. Use something like this instead:

    <html>
    
      <body>
    
        <style>
          h1 {
          text-transform: lowercase;
          }
          h1:first-letter {
          text-transform: uppercase;
          }
        </style>
    
        <h1>Hello World</h1>
      </body>
    </html>

That will result in "Hello World" being displayed as "Hello world".

**Comment by pennersr** [comment]
https://codeberg.org/allauth/django-allauth/issues/867
